# Récupérer les abstract via Crossref

In [1]:
#chargement des modules
import pandas as pd
import datetime
import os
import json
from io import StringIO
import numpy as np
import plotly.express as px
import re

In [2]:
import s3fs #pour connecter au bucket

In [3]:


# Create filesystem object
S3_ENDPOINT_URL = "https://" + os.environ["AWS_S3_ENDPOINT"]
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': S3_ENDPOINT_URL})


BUCKET_OUT = "aluneau"

In [4]:
file_path = BUCKET_OUT + "/" + "Data_bso/fichier_from_mesr/bso-publications-latest_199318270_enriched.jsonl"
print(file_path)
list_id_pub = []
datas =[]
with fs.open(file_path, 'r', encoding='utf-8') as file:
    for line in file:
        try:
            data = json.loads(line)
            # Extract specific fields
            ids = data.get('all_ids')
            list_id_pub.append(ids[0])
            datas.append(data)
            
        except json.JSONDecodeError:
            continue  # Skip invalid lines

aluneau/Data_bso/fichier_from_mesr/bso-publications-latest_199318270_enriched.jsonl

La cellule ci-dessous récupèrent les données qui nous intéressent depuis le fichier Json. Ces données seront ensuitre structurées dans un dataframe constitué d'une ligne par publication. Certaines de ces données ne sont en effet pas disponibles dans le fichier "bso-publications-latest_199318270_enriched.csv".

In [7]:
list_row = []


for n, x in enumerate(list_id_pub):
    dict_pub = datas[n]
    dict_row = {"id":x,
                "pub_type": dict_pub["genre"]
               }
    list_row.append(dict_row)
        
        
df0 = pd.DataFrame.from_dict(list_row)

In [8]:
file_path = BUCKET_OUT + "/" + "Data_bso/fichier_from_mesr/bso-publications-latest_199318270_enriched.csv"
with fs.open(file_path) as csvin:
    df01 = pd.read_csv(csvin, sep =";")

df1 = df01.merge(df0, on = ["id"], how = "left")

In [10]:
import requests
from requests.exceptions import HTTPError
import urllib.parse
import tqdm

In [16]:
CREF_API_ENDPOINT = "https://api.crossref.org/v1/works"


df1b = df1.loc[~df1.doi.isna()]
df1b

,observation_date,id,doi,pmid,hal_id,year,title,journal_issns,journal_issn_l,journal_name,...,software_created,software_shared,data_used,data_created,data_shared,missing_doi_in_hal,has_doi_in_hal,doi_in_hal,bso_country,pub_type
4,2024Q4,doi10.3917/cliop.028.0029,10.3917/cliop.028.0029,NaN,hal-03819403,2022,Du cas Schreber et de ce qu’on ne doit pas ose...,2100-0670,2100-0670,Cliopsy,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,10.3917/cliop.028.0029,fr,journal-article
6,2024Q4,doi10.1590/198053142861,10.1590/198053142861,NaN,hal-03325283,2014,A educação infantil e a questão da escola: o c...,0100-1574,0100-1574,Cadernos de Pesquisa,...,False,False,False,False,False,NaN,1.0,10.1590/198053142861,fr|other,journal-article
12,2024Q4,doi10.1109/tsp.2017.8076097,10.1109/tsp.2017.8076097,NaN,hal-03259338,2017,Multispectral palmprint recognition: A state-o...,NaN,NaN,2017 40th International Conference on Telecomm...,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,10.1109/tsp.2017.8076097,fr,proceedings
19,2024Q4,doi10.4000/hybrid.460,10.4000/hybrid.460,NaN,hal-04173632,2018,Grégory Chatonsky: the art of an archaeofictio...,2276-3538,2276-3538,Hybrid,...,False,False,True,True,False,NaN,1.0,10.4000/hybrid.460,fr|other,journal-article
33,2024Q4,doi10.1016/j.psfr.2014.02.002,10.1016/j.psfr.2014.02.002,NaN,hal-02979729,2014,Apprendre à résoudre des problèmes en favorisa...,0033-2984,0033-2984,Psychologie Française,...,False,False,False,False,False,NaN,1.0,10.1016/j.psfr.2014.02.002,other|fr,journal-article
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45475,2024Q4,doi10.1016/j.compstruct.2015.11.075,10.1016/j.compstruct.2015.11.075,NaN,hal-01912588,2016,Numerical simulation of the nonlinear static b...,0263-8223,0263-8223,Composite Structures,...,True,False,True,False,False,NaN,1.0,10.1016/j.compstruct.2015.11.075,fr|other,journal-article
45486,2024Q4,doi10.3917/sava.056.0039,10.3917/sava.056.0039,NaN,hal-04112191,2021,Les banques centrales dans la pandémie : routi...,1958-7856,1958-5535,Savoir/Agir,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,10.3917/sava.056.0039,fr,journal-article
45488,2024Q4,doi10.1007/s11856-018-1634-z,10.1007/s11856-018-1634-z,NaN,document,2018,Invariant measures for Cartesian powers of Cha...,"0021-2172,1565-8511",0021-2172,Israel Journal of Mathematics,...,False,False,False,False,False,NaN,1.0,10.1007/s11856-018-1634-z,fr|other,journal-article
45494,2024Q4,doi10.4000/pallas.19740,10.4000/pallas.19740,NaN,halshs-03929927,2021,Un idiophone de l’Âge du Bronze en Égée : le s...,"0031-0387,2272-7639",0031-0387,Pallas,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,10.4000/pallas.19740,fr,journal-article
45495,2024Q4,doi10.1007/978-94-017-9585-2_12,10.1007/978-94-017-9585-2_12,NaN,hal-01478739,2015,The Riddle of Attractiveness: Looking for an ‘...,"2211-1948,2211-1956",2211-1948,Current Perspectives on Sexual Selection,...,False,False,True,False,False,NaN,1.0,10.1007/978-94-017-9585-2_12,other|fr,book-chapter

In [18]:

requests.get(CREF_API_ENDPOINT + "/doi/10.3917/cliop.028.0029").json()

{'status': 'ok',
 'message-type': 'work',
 'message-version': '1.0.0',
 'message': {'indexed': {'date-parts': [[2024, 12, 10]],
   'date-time': '2024-12-10T23:59:44Z',
   'timestamp': 1733875184744,
   'version': '3.30.1'},
  'reference-count': 23,
  'publisher': 'CAIRN',
  'issue': '2',
  'content-domain': {'domain': [], 'crossmark-restriction': False},
  'short-container-title': [],
  'abstract': '<jats:p>En un moment historique où la demande adressée aux experts en éducation et formation est de plus en plus présente sous une forme réductionniste et médicalisante, le «\xa0cas Schreber\xa0» permet de repenser les conditions de possibilité de l’éducation d’un enfant. S’il est souvent mobilisé pour montrer les méfaits d’une éducation qualifiée d’autoritaire, pour nous, il est plutôt l’occasion de montrer les risques délétères des initiatives prétendument scientifiques en éducation, structurées autour du déni de la castration, dont son seul témoignage est la condition nécessaire pour qu’un enfant soit convoqué à habiter un lieu de parole singulier dans une histoire en cours.</jats:p>',
  'DOI': '10.3917/cliop.028.0029',
  'type': 'journal-article',
  'created': {'date-parts': [[2022, 10, 14]],
   'date-time': '2022-10-14T10:12:05Z',
   'timestamp': 1665742325000},
  'page': '29-45',
  'source': 'Crossref',
  'is-referenced-by-count': 1,
  'title': ['Du cas Schreber et de ce qu’on ne doit pas oser faire dans l’éducation\xa0: une contribution au débat sur la transmission'],
  'prefix': '10.3917',
  'volume': 'N° 28',
  'author': [{'given': 'Léandro',
    'family': 'de Lajonquière',
    'sequence': 'first',
    'affiliation': []},
   {'given': 'Floriana',
    'family': 'Baldassi D’Arrigo',
    'sequence': 'additional',
    'affiliation': []}],
  'member': '2273',
  'published-online': {'date-parts': [[2022, 10, 5]]},
  'reference': [{'key': 'rb1',
    'unstructured': 'Scilicet, 4 Anonyme (1973). Une étude\xa0: la remarquable famille Schreber. , 287-321.'},
   {'key': 'rb2',
    'unstructured': 'International Journal of Psycho-Analysis, 37 Baumeyer, F. (1956). The Schreber Case. , 61-74.'},
   {'key': 'rb4',
    'unstructured': 'Schreber, father and son. Israëls, H. (1989). Madison, Conn: International Universities Press.'},
   {'key': 'rb6',
    'unstructured': 'Séminaire XX Encore. Lacan, J. (1975). – Paris\xa0: Seuil. [Présentation orale en 1972-1973].'},
   {'key': 'rb8',
    'unstructured': 'Ornicar? 37 Lacan, J. (1986). Deux notes sur l’enfant. , 13-14. [Présentation orale en 1969].'},
   {'key': 'rb3',
    'unstructured': 'Œuvres complètes – 1911-1913, volume Freud, S. (1998). Totem et tabou. Dans XI (p. 189-385). Paris\xa0: PUF. [Texte original publié en 1912].'},
   {'key': 'rb5',
    'unstructured': 'Écrits Lacan, J. (1966). Propos sur la causalité psychique. Dans (p\xa0: 150-192). Paris\xa0: Éditions du Seuil. [Présentation orale en 1946].'},
   {'key': 'rb7',
    'unstructured': 'Séminaire III – Les psychoses. Lacan, J. (1981). Paris\xa0: Seuil. [Présentation orale en 1955-1956].'},
   {'key': 'rb9',
    'unstructured': 'Autres écrits Lacan, J. (2001). Joyce le Symptôme. Dans J. Lacan, (p. 565-570). Paris\xa0: Éditions du Seuil. [Texte original publié en 1975].'},
   {'key': 'rb11',
    'doi-asserted-by': 'publisher',
    'first-page': '79-88',
    'DOI': '10.3917/cliop.021.0079',
    'article-title': 'Les études psychanalytiques en éducation et formation au Brésil',
    'volume': 'N° 21',
    'author': 'de Lajonquière Léandro',
    'year': '2019',
    'journal-title': 'Cliopsy',
    'ISSN': 'https://id.crossref.org/issn/2100-0670',
    'issn-type': 'print'},
   {'key': 'rb12',
    'unstructured': 'As abelhas não fazem fofoca. Estudos psicanalíticos no campo da educação de Lajonquière, L. (2021). De um psicanalista na educação. Dans J. Rosado et M. Pessoa (dir.), (p. 13-38). São Paulo: Instituto Langage.'},
   {'key': 'rb13',
    'unstructured': 'Estilos da Clínica, 27 de Lajonquière, L. (2022). La psychanalyse, la pensée scientifique et le réel\xa0: une note propédeutique au débat sur l’expérience éducative. (3).'},
   {'key': 'rb14',
    'unstructured': 'Psychanalyse et subversion des normes. de Lajonquière, L. (2023). Il n’y a d’éducation que hors-normes. Dans C. Alberti et A. Pfauwadel, St-Denis\xa0: PUV [sous presse].'},
   {'key': 'rb15',
    'unstructured': 'The Journal of Psychohistory, 16(3) Lothane, Z. (1988). Vindicating Schreber’s Father: Neither Sadist Nor Child Abuser. , 263-288.'},
   {'key': 'rb16',
    'unstructured': 'In Defence of Schreber. Soul Murder and Psychiatry. Lothane, Z. (1992). Hillsdale, London: The Analytic Press.'},
   {'key': 'rb18',
    'doi-asserted-by': 'publisher',
    'first-page': '9-14',
    'DOI': '10.3917/cliop.027.0009',
    'article-title': 'Le «\xa0cas Schreber\xa0», source d’inspiration pour la psychanalyse et pour l’éducation',
    'volume': 'N° 27',
    'author': 'Méloni Dominique',
    'year': '2022',
    'journal-title': 'Cliopsy',
    'ISSN': 'https://id.crossref.org/issn/2100-0670',
    'issn-type': 'print'},
   {'key': 'rb19',
    'doi-asserted-by': 'publisher',
    'first-page': '492-499',
    'DOI': '10.1177/000306516000800306',
    'article-title': "Schreber's Father",
    'volume': '8',
    'author': 'Niederland William G.',
    'year': '1960',
    'journal-title': 'Journal of the American Psychoanalytic Association',
    'ISSN': 'https://id.crossref.org/issn/0003-0651',
    'issn-type': 'print'},
   {'key': 'rb20',
    'doi-asserted-by': 'crossref',
    'unstructured': 'Estilos da Clínica Ponnou, S. et Niewiadomski, C. (2020). Cliniques de la transmission\xa0: ce qui se transmet, c’est de la jouissance. , 25(2), 246-263.',
    'DOI': '10.11606/issn.1981-1624.v25i2p246-263'},
   {'key': 'rb22',
    'unstructured': 'L’esprit assassiné. Schatzman, M. (1974). Paris\xa0: Édition Stock.'},
   {'key': 'rb24',
    'doi-asserted-by': 'publisher',
    'first-page': '29-45',
    'DOI': '10.3917/cliop.028.0029',
    'article-title': 'Du cas Schreber et de ce qu’on ne doit pas oser faire dans l’éducation\xa0: une contribution au débat sur la transmission',
    'volume': 'N° 28',
    'author': 'de Lajonquière Léandro',
    'year': '2022',
    'journal-title': 'Cliopsy',
    'ISSN': 'https://id.crossref.org/issn/2100-0670',
    'issn-type': 'print'},
   {'key': 'rb17',
    'unstructured': 'Éducation impossible. Mannoni, M. (1973). Paris\xa0: Seuil.'},
   {'key': 'rb21',
    'unstructured': 'L’anti-nature – Éléments pour une philosophie tragique. Rosset, C. (1973). Paris\xa0: PUF.'},
   {'key': 'rb23',
    'unstructured': 'Frankenstein, or the Modern Prometheus. Shelley, M. (1998). New York: Oxford University Press. [Texte original publié en 1818].'}],
  'container-title': ['Cliopsy'],
  'original-title': [],
  'deposited': {'date-parts': [[2023, 10, 2]],
   'date-time': '2023-10-02T06:44:15Z',
   'timestamp': 1696229055000},
  'score': 1,
  'resource': {'primary': {'URL': 'https://www.cairn.info/revue-cliopsy-2022-2-page-29.htm?ref=doi'}},
  'subtitle': [''],
  'short-title': [],
  'issued': {'date-parts': [[2022, 10, 5]]},
  'references-count': 23,
  'journal-issue': {'issue': '2',
   'published-online': {'date-parts': [[2022, 10, 5]]}},
  'URL': 'https://doi.org/10.3917/cliop.028.0029',
  'relation': {},
  'ISSN': ['2100-0670'],
  'issn-type': [{'type': 'electronic', 'value': '2100-0670'}],
  'subject': [],
  'published': {'date-parts': [[2022, 10, 5]]}}}

In [30]:
list_row = []
list_author = []
for n, x in enumerate(tqdm.tqdm(df1b.id, total=len(df1b))):
    doi = df1b.doi.iloc[n]
    query_response = requests.get(CREF_API_ENDPOINT + '/' + doi).json()
    try:
        abstract = query_response["message"]["abstract"].replace('<jats:p>','').replace('</jats:p>','')
    except:
        abstract = "no abstract"

    dict_row = {"id":x,
               "doi":doi,
               "abstract":abstract,
                "source":query_response["message"]['resource']['primary']['URL']
               }
    list_row.append(dict_row)
    try:
        for a in query_response["message"]["author"]:
            if len(a["affiliation"]) > 0 :
                affil = a["affiliation"][0]['name']
            else:
                affil = "no affil"
            dic_author = {'id':x,
                          'doi':doi,
                          'given_name':a["given"],
                          'family_name':a['family'],
                          'affiliation': affil
                         }
            list_author.append(dic_author)
    except:
        dic_author = {'id':x,
                          'doi':doi,
                          'given_name':'no author',
                          'family_name':'no author',
                          'affiliation': 'no affil'
                     }
        list_author.append(dic_author)

100%|██████████| 11009/11009 [57:33<00:00,  3.19it/s]

In [36]:
dfabs = pd.DataFrame.from_dict(list_row)
dfabs.loc[dfabs.abstract!="no abstract"]

,id,doi,abstract,source
0,doi10.3917/cliop.028.0029,10.3917/cliop.028.0029,En un moment historique où la demande adressée...,https://www.cairn.info/revue-cliopsy-2022-2-pa...
1,doi10.1590/198053142861,10.1590/198053142861,"Nos últimos trinta anos, a prioridade dada a u...",http://www.scielo.br/scielo.php?script=sci_art...
3,doi10.4000/hybrid.460,10.4000/hybrid.460,"In the wake of postmodernist experiments, Chat...",https://journals.openedition.org/hybrid/460
7,doi10.4000/danse.4410,10.4000/danse.4410,Il est admis par l’historiographie que les hér...,https://journals.openedition.org/danse/4410
9,doi10.3917/arss.228.0004,10.3917/arss.228.0004,"Peu étudiés, les immigrés et descendants d’imm...",https://www.cairn.info/revue-actes-de-la-reche...
...,...,...,...,...
10999,doi10.3917/ls.173.0205,10.3917/ls.173.0205,Le contexte même des échanges électroniques (i...,https://www.cairn.info/revue-langage-et-societ...
11000,doi10.1177/0073275317751316,10.1177/0073275317751316,Using as case studies the initiatives develop...,https://journals.sagepub.com/doi/10.1177/00732...
11002,doi10.3917/cdlj.1901.0117,10.3917/cdlj.1901.0117,Résumé Nous souhaitons dans cet article expose...,https://droit.cairn.info/revue-les-cahiers-de-...
11003,doi10.3390/commodities2020010,10.3390/commodities2020010,Asset markets have long contained a section de...,https://www.mdpi.com/2813-2432/2/2/10
11007,doi10.4000/pallas.19740,10.4000/pallas.19740,Parmi les instruments de l’Âge du Bronze égéen...,https://journals.openedition.org/pallas/19740

In [35]:
dfauthor = pd.DataFrame.from_dict(list_author)
len(dfauthor.loc[dfauthor.affiliation!="no affil"])/len(dfauthor)

0.19884835809544504

In [45]:
dfabs["lang"]= dfabs.id.map(dict(zip(df1.id, df1.lang)).get)
dfabs["type"]= dfabs.id.map(dict(zip(df1.id, df1.pub_type)).get)

In [47]:
dfabs.loc[(dfabs.abstract!="no abstract") & (dfabs.lang=="fr")]

,id,doi,abstract,source,lang,type
0,doi10.3917/cliop.028.0029,10.3917/cliop.028.0029,En un moment historique où la demande adressée...,https://www.cairn.info/revue-cliopsy-2022-2-pa...,fr,journal-article
7,doi10.4000/danse.4410,10.4000/danse.4410,Il est admis par l’historiographie que les hér...,https://journals.openedition.org/danse/4410,fr,journal-article
9,doi10.3917/arss.228.0004,10.3917/arss.228.0004,"Peu étudiés, les immigrés et descendants d’imm...",https://www.cairn.info/revue-actes-de-la-reche...,fr,NaN
12,doi10.3917/sr.040.0111,10.3917/sr.040.0111,Résumé La production critique des femmes sur l...,https://www.cairn.info/revue-societes-et-repre...,fr,NaN
15,doi10.3917/machr.244.0025,10.3917/machr.244.0025,Avant de se trouver contesté visiblement au cœ...,https://www.cairn.info/revue-maghreb-machrek-2...,fr,journal-article
...,...,...,...,...,...,...
10995,doi10.3917/anso.181.0155,10.3917/anso.181.0155,Alors que le Programme national pour la rénova...,https://www.cairn.info/revue-l-annee-sociologi...,fr,journal-article
10997,doi10.4000/echogeo.15296,10.4000/echogeo.15296,"Le 19 septembre 2017, trente-deux ans jour pou...",https://journals.openedition.org/echogeo/15296,fr,journal-article
10999,doi10.3917/ls.173.0205,10.3917/ls.173.0205,Le contexte même des échanges électroniques (i...,https://www.cairn.info/revue-langage-et-societ...,fr,journal-article
11002,doi10.3917/cdlj.1901.0117,10.3917/cdlj.1901.0117,Résumé Nous souhaitons dans cet article expose...,https://droit.cairn.info/revue-les-cahiers-de-...,fr,journal-article
11007,doi10.4000/pallas.19740,10.4000/pallas.19740,Parmi les instruments de l’Âge du Bronze égéen...,https://journals.openedition.org/pallas/19740,fr,journal-article

In [51]:
file_path = BUCKET_OUT + "/" + "Data_bso/outputs/enriched_data/abstracts/2026-03-11_publis_with_abstract.csv"
with fs.open(file_path, "w") as file_out:
    dfabs.to_csv(file_out, sep=",", index= False)

In [52]:
file_path = BUCKET_OUT + "/" + "Data_bso/outputs/enriched_data/geolocation/2026-03-11_affil_crossref.csv"
with fs.open(file_path, "w") as file_out:
    dfauthor.to_csv(file_out, sep=",", index= False)