# Récupérer les données géographiques (pays, villes)

In [1]:
#chargement des modules
import pandas as pd
import datetime
import os
import json
from io import StringIO
import numpy as np
import plotly.express as px
import re

In [2]:
import s3fs #pour connecter au bucket

In [3]:


# Create filesystem object
S3_ENDPOINT_URL = "https://" + os.environ["AWS_S3_ENDPOINT"]
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': S3_ENDPOINT_URL})

BUCKET_OUT = "aluneau"

In [4]:
with fs.open(f"{BUCKET_OUT}/Data_bso/outputs/enriched_data/geolocation/2026-03-11_publi_from_bso_with_address.csv", "r") as file_in:
    df0 = pd.read_csv(file_in, sep=",")

In [5]:
file_path = BUCKET_OUT + "/" + "Data_bso/fichier_from_mesr/bso-publications-latest_199318270_enriched.csv"
with fs.open(file_path) as csvin:
    df1 = pd.read_csv(csvin, sep =";")

df1.columns

Index(['observation_date', 'id', 'doi', 'pmid', 'hal_id', 'year', 'title',
       'journal_issns', 'journal_issn_l', 'journal_name', 'publisher',
       'publisher_dissemination', 'bso_classification', 'lang', 'genre',
       'amount_apc_EUR', 'apc_source', 'domains', 'detected_countries',
       'bso_local_affiliations', 'rors', 'funding_anr', 'funding_europe',
       'bsso_classification', 'is_oa', 'is_oa_hal', 'oa_host_type',
       'journal_is_in_doaj', 'journal_is_oa', 'unpaywall_oa_status',
       'oa_colors', 'licence_publisher', 'licence_repositories',
       'repositories', 'software_mentions', 'data_mentions', 'software_used',
       'software_created', 'software_shared', 'data_used', 'data_created',
       'data_shared', 'missing_doi_in_hal', 'has_doi_in_hal', 'doi_in_hal',
       'bso_country'],
      dtype='object')

## Retrouver les informations géographiques à partir du ROR

L'objectif est d'utiliser l'api de ROR pour récupérer des données géographiques à partir de l'identifiation ROR des institutions. Le problème est que toutes les institutions recencées dans le BSO n'ont pas de ROR. L'analyse des données montre qu'on dispose du ROR uniquement pour les établissement français.

On utilise la librairie requests pour interroger l'API

In [6]:
df01 = df0[["id","rors"]]
df01["rors"] = df01.rors.str.split("|")
df_ror = df01.explode("rors")

/tmp/ipykernel_11041/4143035616.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df01["rors"] = df01.rors.str.split("|")

In [7]:
import requests
from requests.exceptions import HTTPError
import urllib.parse
import tqdm

In [8]:
ROR_API_ENDPOINT = "https://api.dev.ror.org/organizations"


params = {"query":"1m84wm78"} # le nombre de ligne. Par défaut, l'api affiche les 30 première ligne et le maximum fixé est de 10000.

In [9]:
query_response = requests.get(ROR_API_ENDPOINT + '/' + "01m84wm78").json()

On affiche la structure des données

In [10]:
query_response

{'admin': {'created': {'date': '2018-11-14', 'schema_version': '1.0'},
  'last_modified': {'date': '2026-01-29', 'schema_version': '2.1'}},
 'domains': [],
 'established': 1969,
 'external_ids': [{'all': ['grid.11619.3e'],
   'preferred': 'grid.11619.3e',
   'type': 'grid'},
  {'all': ['0000 0001 2152 2279'], 'preferred': None, 'type': 'isni'},
  {'all': ['Q459026'], 'preferred': None, 'type': 'wikidata'}],
 'id': 'https://ror.org/01m84wm78',
 'links': [{'type': 'website', 'value': 'http://www.univ-rennes2.fr/'},
  {'type': 'wikipedia',
   'value': 'http://en.wikipedia.org/wiki/University_of_Rennes_2_%E2%80%93_Upper_Brittany'}],
 'locations': [{'geonames_details': {'continent_code': 'EU',
    'continent_name': 'Europe',
    'country_code': 'FR',
    'country_name': 'France',
    'country_subdivision_code': 'BRE',
    'country_subdivision_name': 'Brittany',
    'lat': 48.11198,
    'lng': -1.67429,
    'name': 'Rennes'},
   'geonames_id': 2983990}],
 'names': [{'lang': 'en',
   'types': ['label'],
   'value': 'University of Rennes 2'},
  {'lang': 'fr',
   'types': ['label', 'ror_display'],
   'value': 'Université Rennes 2'}],
 'relationships': [{'label': 'Laboratoire de Psychologie : Cognition, Comportement, Communication',
   'type': 'child',
   'id': 'https://ror.org/03dgmxj03'},
  {'label': 'Institut de recherche mathématique de Rennes',
   'type': 'child',
   'id': 'https://ror.org/05y76vp22'},
  {'label': 'Laboratoire Mouvement Sport Santé',
   'type': 'child',
   'id': 'https://ror.org/05b3p7p58'},
  {'label': 'Anglophonie: communautés, écritures',
   'type': 'child',
   'id': 'https://ror.org/0595x5h51'},
  {'label': 'Arts: pratiques et poétiques',
   'type': 'child',
   'id': 'https://ror.org/01k9kg969'},
  {'label': 'Arènes: politique, santé publique, environnement, médias',
   'type': 'child',
   'id': 'https://ror.org/00m4rxj18'},
  {'label': 'Centre d’études des langues et littératures anciennes et modernes',
   'type': 'child',
   'id': 'https://ror.org/045q3tp69'},
  {'label': 'Centre d’Etudes des Langues, Territoires et Identités Culturelles – Bretagne et Langues Minoritaires',
   'type': 'child',
   'id': 'https://ror.org/05r4re112'},
  {'label': 'Centre de Recherche en Archéologie, Archéosciences, Histoire',
   'type': 'child',
   'id': 'https://ror.org/02wgtm643'},
  {'label': 'Centre de recherche sur l’éducation, les apprentissages et la didactique',
   'type': 'child',
   'id': 'https://ror.org/00psw8792'},
  {'label': 'Équipe de Recherche Interlangue : Mémoires, Identités, Territoires',
   'type': 'child',
   'id': 'https://ror.org/0339jw085'},
  {'label': 'Espaces et Sociétés',
   'type': 'child',
   'id': 'https://ror.org/03237mt20'},
  {'label': 'Histoire et critique des arts',
   'type': 'child',
   'id': 'https://ror.org/018n13n96'},
  {'label': 'Littoral, Environnement, Télédétection, Géomatique',
   'type': 'child',
   'id': 'https://ror.org/05sat2s07'},
  {'label': 'Linguistique Ingénierie et Didactique des Langues',
   'type': 'child',
   'id': 'https://ror.org/02gn4cf81'},
  {'label': 'Laboratoire Interdisciplinaire de Recherche en Innovations Sociétales',
   'type': 'child',
   'id': 'https://ror.org/01dyfj824'},
  {'label': 'Pôle de Recherche Francophonies, Interculturel, Communication, Sociolinguistique',
   'type': 'child',
   'id': 'https://ror.org/01pxcyx49'},
  {'label': "Pratiques et Théories de l'art contemporain",
   'type': 'child',
   'id': 'https://ror.org/00drkdp66'},
  {'label': 'Recherches en Psychopathologie et Psychanalyse',
   'type': 'child',
   'id': 'https://ror.org/04fke6556'},
  {'label': 'Tempora', 'type': 'child', 'id': 'https://ror.org/05rmjk207'},
  {'label': 'Valeurs, Innovations, Politiques, Socialisations et Sports',
   'type': 'child',
   'id': 'https://ror.org/026m1rk14'},
  {'label': "Observatoire des Sciences de l'Environnement de Rennes",
   'type': 'child',
   'id': 'https://ror.org/05pwkex33'},
  {'label': 'Maison des sciences humaines et sociales en Bretagne',
   'type': 'child',
   'id': 'https://ror.org/01jwwzm25'}],
 'status': 'active',
 'types': ['education']}

In [11]:
for n, x in enumerate(query_response["names"]):
    if 'ror_display' in x["types"]:
        print(x)

{'lang': 'fr', 'types': ['label', 'ror_display'], 'value': 'Université Rennes 2'}

Nous voulons récupérer les informations contenues dans "locations" :

```
locations': [{'geonames_details': {'continent_code': 'EU',
    'continent_name': 'Europe',
    'country_code': 'FR',
    'country_name': 'France',
    'country_subdivision_code': 'BRE',
    'country_subdivision_name': 'Brittany',
    'lat': 48.11198,
    'lng': -1.67429,
    'name': 'Rennes'},

```

In [12]:
dict_ror = {}
list_row = []
for ror in tqdm.tqdm(df_ror.rors.unique(), total = df_ror.rors.nunique()):
    dict_row ={}
    rorid = ror.split("/")[-1]
    #print(rorid)
    dict_ror[ror] = rorid
    dict_row["rors"] = ror
    data = requests.get(ROR_API_ENDPOINT + '/' + rorid).json()

    for n, x in enumerate(data["names"]):
        if 'ror_display' in x["types"]:
            dict_row["nom"] = x["value"]
    locations_data = data["locations"][0]["geonames_details"]
    for i in locations_data:
        dict_row[i] = locations_data[i]
        if i == "name":
            dict_row["city"] = locations_data[i]
    dict_row["geonames_id"] = data["locations"][0]["geonames_id"]
    list_row.append(dict_row)

100%|██████████| 155/155 [00:20<00:00,  7.50it/s]

In [13]:
df_inst = pd.DataFrame.from_dict(list_row)

In [14]:
df_inst.country_name.value_counts()
df_inst

,rors,nom,continent_code,continent_name,country_code,country_name,country_subdivision_code,country_subdivision_name,lat,lng,name,city,geonames_id
0,https://ror.org/04wez5e68,Université Paris 8,EU,Europe,FR,France,IDF,Île-de-France,48.85341,2.34880,Paris,Paris,2988507
1,https://ror.org/02wwzvj46,Université de Tours,EU,Europe,FR,France,CVL,Centre-Val de Loire,47.39484,0.70398,Tours,Tours,2972191
2,https://ror.org/057qpr032,Université de Bordeaux,EU,Europe,FR,France,NAQ,Nouvelle-Aquitaine,44.84124,-0.58046,Bordeaux,Bordeaux,3031582
3,https://ror.org/05ggc9x40,Université Paris-Est Créteil,EU,Europe,FR,France,IDF,Île-de-France,48.79266,2.46569,Créteil,Créteil,3022530
4,https://ror.org/01qhqcj41,Université de Technologie de Troyes,EU,Europe,FR,France,GES,Grand Est,48.30073,4.08524,Troyes,Troyes,2971549
...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,https://ror.org/03pnp1a74,Lamsade,EU,Europe,FR,France,IDF,Île-de-France,48.85341,2.34880,Paris,Paris,2988507
151,https://ror.org/042xmz674,Laboratoire de Physique et Chimie des Nano-Objets,EU,Europe,FR,France,OCC,Occitanie,43.60426,1.44367,Toulouse,Toulouse,2972315
152,https://ror.org/04fm0sh33,Laboratoire de Planétologie et Géosciences,EU,Europe,FR,France,PDL,Pays de la Loire,47.21725,-1.55336,Nantes,Nantes,2990969
153,https://ror.org/022zdgq74,École Nationale de l’Aviation Civile,EU,Europe,FR,France,OCC,Occitanie,43.60426,1.44367,Toulouse,Toulouse,2972315
154,https://ror.org/052xwpe12,EM Normandie Business School,EU,Europe,FR,France,NOR,Normandy,49.49346,0.10785,Le Havre,Le Havre,3003796

In [15]:
with fs.open(f"{BUCKET_OUT}/Data_bso/outputs/enriched_data/geolocation/2026-03-11_geographical_info_french_affiliation.csv", "w") as file_out:
    df_inst.to_csv(file_out, sep=",", index= False)

In [16]:
with fs.open(f"{BUCKET_OUT}/Data_bso/outputs/enriched_data/geolocation/2026-03-11_publication_with_french_affiliation.csv", "w") as file_out:
    df_ror.merge(df_inst, on = ["rors"], how = "left").drop_duplicates().to_csv(file_out, sep=",", index= False)

## Retrouver le ror à partir du nom des universités

Dans les données enrichies, le ror est présent uniquement pour les établissement français. On va essayer de récupérer le ror à partir de l'adresse des structures (lorsqu'elle est indiquée).
Pour cela, nous allons utilisés plus informations et plusieurs technique. L'objectif est de récupérer le nomn de l'établissement et la ville.

Lorsqu'il y a une adresse dans les données du bso (variable nommée `address`), nous l'utilisons en priorité. S'il n'y en a pas ou que les informations contenues ne permettent de retrouver des indications géographiques, on utilise l'affiliation retrouvée via Crossref.


**Pour certaines lignes, le texte présent dans les colonne "struc_address" et "address" correspondent en fait soit au titre soit au résumé de la plublication.**


Concernant les techniques, on utilise d'abord les regex, puis des outils de reconnaissance d'entité nommée (Spacy)

In [17]:
file_path = BUCKET_OUT + "/" + "Data_bso/outputs/enriched_data/geolocation/2026-03-11_affil_crossref.csv"
with fs.open(file_path) as csvin:
    dfcr = pd.read_csv(csvin, sep =",")


dfcr1 = dfcr.loc[dfcr.affiliation!="no affil"]

df01 = df0.merge(dfcr1[["id","affiliation"]], on = ["id"], how = "left").merge(df1[["id","title"]], on = ["id"], how = "left")#.reset_index()

In [18]:
df02 = df01[["id","struc_address","affiliation","title"]]
df02["address"] = df02.struc_address.str.split("|")
df_ad = df02[['id','affiliation','title','address']].explode("address").drop_duplicates().dropna(subset="address").reset_index().drop(columns=["index"])

#On isole les adresses françaises
df_adfr = df_ad.loc[(df_ad.address.str.lower().str.contains("france|paris"))].reset_index().drop(columns=["index"])

df_adfr

/tmp/ipykernel_11041/4099095763.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df02["address"] = df02.struc_address.str.split("|")

,id,affiliation,title,address
0,halhal-03933378,NaN,Typo-chronologie des tombes à inhumation en ré...,Institut national de recherches archéologiques...
1,halhal-03933378,NaN,Typo-chronologie des tombes à inhumation en ré...,"Cités, Territoires, Environnement et Sociétés,..."
2,halhal-03933378,NaN,Typo-chronologie des tombes à inhumation en ré...,Service de l'archéologie du département d'Indr...
3,halhal-03933378,NaN,Typo-chronologie des tombes à inhumation en ré...,EVEHA (Etudes et valorisations archeologiques)...
4,halhal-03933378,NaN,Typo-chronologie des tombes à inhumation en ré...,"Service Archéologique Municipal d'Orléans, 13 ..."
...,...,...,...,...
56312,halhal-04366816,NaN,The Language of Bias: Unveiling Implicit Attit...,"Laboratoire sur les Interactions Cognition, Ac..."
56313,halhal-02120667,NaN,The archaeological project at Ra's al-Jinz RJ3...,"Archéologies et Sciences de l'Antiquité, UMR70..."
56314,halhal-02120667,NaN,The archaeological project at Ra's al-Jinz RJ3...,"Environnement, Ville, Société, UMR5600, UMR560..."
56315,halhal-02120667,NaN,The archaeological project at Ra's al-Jinz RJ3...,"LIttoral ENvironnement et Sociétés, UMR7266, L..."
56316,halhal-01964707,NaN,Annotating Multimodal data of Singing and Spea...,"Structures Formelles du Langage, UMR7023, UMR7..."

In [19]:
df_adfr["rank_id"] = df_adfr.index.astype(str)
df_adfr["name_umr"] = df_adfr.apply(lambda row:"|".join(set([x.replace(" ","") for x in re.findall(r"(?:umr|ums|ea).\d+\b", str(row.address).lower())])),1)

df_adfr.loc[df_adfr.name_umr.str.contains("ums")]

,id,affiliation,title,address,rank_id,name_umr
878,halmedihal-01925578,NaN,"Film réalisé dans le cadre de ""14-18 Mission C...","Archeovision CNRS, UMS3657 / UPS3551, UB, UBM,...",878,ums3657
1123,halhal-02180687,NaN,La lecture numérique,Laboratoire des Usages en Technologies d'Infor...,1123,ums2809
1645,halhal-01315200,NaN,Cultural evolution and burial discontinuities ...,"Eco-Anthropologie et Ethnobiologie, UMS104, UM...",1645,umr7206|ums104
2023,halhal-03101060,NaN,Activités illégales dans/autour d’une aire pro...,"Eco-Anthropologie et Ethnobiologie, UMS104, UM...",2023,umr7206|ums104
2348,halhal-00869953,NaN,Visual attention in a complex task: discrimina...,Laboratoire des Usages en Technologies d'Infor...,2348,ums2809
...,...,...,...,...,...,...
54571,halhal-04657865,NaN,Synthèse du groupe de travail RnMSH sur les re...,"Structuration et Internationalisation des SHS,...",54571,ums3603
54611,halhal-03378997,NaN,Restauration écologique de la rivière Sélune. ...,Réseau interdisciplinaire pour l’aménagement e...,54611,ums2414
54781,halhalshs-01374894,NaN,"Étude de cas : l’anticartogramme, un exemple p...",Réseau interdisciplinaire pour l'aménagement e...,54781,ums2414
54919,halhal-04270523,NaN,Les fers médiévaux de Notre-Dame de Paris : ch...,"Laboratoire de mesure du carbone 14, DSM/LSCE,...",54919,ums2572
55747,halhal-03714423,NaN,"Hyères, Olbia de Provence / Parking du bord de...","Centre Jean Berard, UMS1797, CJB, EFR, CNRS, E...",55747,ums1797

In [20]:
df_adfr["address"] = df_adfr.apply(lambda row: re.sub("Paris VIII", "Paris 8", str(row.address)),1)
df_adfr["address"] = df_adfr.apply(lambda row: re.sub("Paris XIII", "Paris 13", str(row.address)),1)
df_adfr["address"] = df_adfr.apply(lambda row: re.sub("Paris X", "Paris Nanterre", str(row.address)),1)

In [21]:
df_frwithoutumr = df_adfr.loc[df_adfr.name_umr==""]

In [22]:
!python -m spacy download fr_core_news_md

Collecting fr-core-news-md==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/fr_core_news_md-3.8.0/fr_core_news_md-3.8.0-py3-none-any.whl (45.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 MB 55.4 MB/s  0:00:00m0:00:0100:01
✔ Download and installation successful
You can now load the package via spacy.load('fr_core_news_md')

In [23]:
import spacy

In [24]:
regex_match = {}

for index, row in df_adfr.iterrows():
    #print("######", row.address)
    address = re.sub(r"'|’", " ", str(row.address))
    split_address = set(re.sub(r"\s\-\s|;", ",",address.lower()).split(","))
    lower_address = ", ".join(split_address)
    regex = r"(?:univ\w*|collège|institut|école|school)[\s\w-]*\b"
    regex2=r'\b[\s\w-]+(?:univ\w*|collège|institut|école|school)\b'
    find_univ = re.findall(regex, lower_address)
    find_univ2 = [x.strip() for x in re.findall(regex2, lower_address) if x not in find_univ]

    list_univ = set(find_univ + find_univ2)
    if len(list_univ) > 0 :
        regex_match[row.rank_id]= "|".join(list_univ)
    else:
        pass
regex_match
df_adfr["etab"] = df_adfr.rank_id.map(regex_match.get)

In [25]:
t_etab = df_adfr[["id", "rank_id","etab"]]
t_etab["etab"] = t_etab.etab.str.split("|")
t_etab1 = t_etab.loc[~t_etab.etab.isna()].explode("etab").drop_duplicates().reset_index().drop(columns=["index"])
list_etab = [x for x in t_etab1.etab.unique()]
print(len(list_etab))

2075

/tmp/ipykernel_11041/1054126011.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_etab["etab"] = t_etab.etab.str.split("|")

In [26]:
file_path = BUCKET_OUT + "/" + "Data_bso/referentiels/fr-esr-principaux-etablissements-enseignement-superieur.csv"
with fs.open(file_path) as csvin:
    ref = pd.read_csv(csvin, sep =";")

ref.columns

Index(['etablissement_id_paysage', 'uo_lib', 'nom_court', 'sigle',
       'type_d_etablissement', 'typologie_d_universites_et_assimiles',
       'secteur_d_etablissement', 'vague_contractuelle', 'localisation', 'url',
       'coordonnees', 'uai', 'anciens_codes_uai', 'siret', 'siren', 'rna',
       'identifiant_wikidata', 'element_wikidata', 'identifiant_idref',
       'identifiant_eter', 'identifiant_ror', 'element_ror', 'identifiant_pic',
       'identifiant_orgref', 'identifiant_isni', 'element_isni',
       'element_fundref', 'date_creation', 'texte_de_ref_creation_lib',
       'texte_de_ref_creation', 'com_code', 'com_nom', 'uucr_id', 'uucr_nom',
       'dep_id', 'dep_nom', 'aca_id', 'aca_nom', 'reg_id', 'reg_nom',
       'reg_id_old', 'reg_nom_old', 'mention_distribution', 'adresse_uai',
       'lieu_dit_uai', 'boite_postale_uai', 'code_postal_uai',
       'localite_acheminement_uai', 'pays_etranger_acheminement',
       'numero_telephone_uai', 'statut_juridique_court',
       'statut_juridique_long', 'compte_facebook', 'compte_twitter',
       'compte_instagram', 'compte_flickr', 'compte_pinterest', 'flux_rss',
       'compte_linkedin', 'compte_france_culture', 'compte_scribd',
       'compte_scoopit', 'compte_tumblr', 'compte_youtube', 'compte_vimeo',
       'compte_dailymotion', 'compte_github', 'wikipedia', 'wikipedia_en',
       'scanr', 'hal', 'mooc', 'article', 'uo_lib_officiel', 'uo_lib_en',
       'url_en', 'url_cn', 'url_es', 'url_de', 'url_it',
       'universites_fusionnees', 'etablissement_experimental',
       'champ_recherche', 'inscrits', 'inscrits_2010', 'inscrits_2011',
       'inscrits_2012', 'inscrits_2013', 'inscrits_2014', 'inscrits_2015',
       'inscrits_2016', 'inscrits_2017', 'inscrits_2018', 'inscrits_2019',
       'inscrits_2020', 'inscrits_2021', 'inscrits_2022'],
      dtype='object')

In [27]:

cleaned_list_etab = [re.sub(r'\s+', ' ', re.sub(r"d'|l'|\bl\b|\bd\b|\bde\b|\bdes\b", " ", x)) for x in list_etab]


dict_etab = {}

for index, row in ref.iterrows():
    univ = re.sub(r"d'|l'|\bde\b|\bdes\b", " ",row.uo_lib.lower())
    cleaned_univ = re.sub(r'\s+', ' ', univ)
    #cleaned_list_etab = [re.sub(r'\s*', ' ', re.sub(r"d'|l'|\bde\b|\bdes\b", " ", x)) for x in list_etab]
    find_etab = [x for x in cleaned_list_etab if re.match(cleaned_univ, x)]
    for etab in find_etab:
        dict_etab[etab]= row.uo_lib

dict_etab
t_etab1["cleaned_etab"] = t_etab1.apply(lambda row: re.sub(r'\s+', ' ', re.sub(r"d'|l'|\bl\b|\bd\b|\bde\b|\bdes\b", " ", str(row.etab))),1)
t_etab1["norm_name"] = t_etab1.cleaned_etab.map(dict_etab.get)
t_etab1["id_rors"] = t_etab1.norm_name.map(dict(zip(ref.uo_lib, ref.identifiant_ror)).get)
#t_etab1["rors"] = "https://ror.org/" + t_etab1.id_rors.astype(str)
t_etab1

,id,rank_id,etab,cleaned_etab,norm_name,id_rors
0,halhal-03933378,0,institut national de recherches archéologiques...,institut national recherches archéologiques pr...,None,None
1,halhal-03933378,1,université de tours,université tours,Université de Tours,02wwzvj46
2,halhal-03933378,7,université paris 1 panthéon-sorbonne,université paris 1 panthéon-sorbonne,None,None
3,halhal-03933378,7,université paris 8 vincennes-saint-denis,université paris 8 vincennes-saint-denis,Université Paris 8,04wez5e68
4,halhal-03933378,7,université 92023 nanterre cedex,université 92023 nanterre cedex,None,None
...,...,...,...,...,...,...
118204,halhal-02120667,56314,université jean monnet,université jean monnet,None,None
118205,halhal-02120667,56315,université,université,None,None
118206,halhal-02120667,56315,la rochelle université,la rochelle université,La Rochelle Université,04mv1z119
118207,halhal-01964707,56316,université paris lumières,université paris lumières,None,None
118208,halhal-01964707,56316,université paris 8 vincennes-saint-denis,université paris 8 vincennes-saint-denis,Université Paris 8,04wez5e68

In [30]:
list_etab1 = list(set([x for x in t_etab1.etab.loc[t_etab1.id_rors.isna()]]))
print(len(list_etab1))
dict_ror2 = {}
for m, etab in tqdm.tqdm(enumerate(list_etab1), total = len(list_etab1)):
    row_id = m
    l_apostrophe = re.sub(r"\sl\s", " l'", etab)
    cleaned_etab = re.sub(r"\sd\s", " l'", l_apostrophe)
    response = requests.get(ROR_API_ENDPOINT + '?' + f'query="{cleaned_etab}"' + "&filter=country.country_code:fr").json()
    if response["number_of_results"] > 1 :
        for n, x in enumerate(response["items"]):
            if 'education' in x["types"] :
                datas = response["items"][n]
                rors = datas["id"]
    elif response["number_of_results"] == 1 :
        datas = response["items"][0]
        rors = datas["id"]
    else:
         rors = "not found"
    dict_ror2[etab] = rors
    #print(cleaned_etab, rors)

1717

100%|██████████| 1717/1717 [03:12<00:00,  8.92it/s]

In [31]:
dict_ror2

{'labsic université': 'not found',
 'université d¹evry val d¹essonne': 'not found',
 'institut caennais de recherche juridique': 'https://ror.org/034p80033',
 'umr 7317 cnrs et aix-marseille université': 'not found',
 'école normale supérieure-psl du ministère de la culture du ministère des affaires étrangères': 'not found',
 'université paris professeur à l institut': 'not found',
 'institut d études ibériques et latino-américaines 31': 'not found',
 'université abdou moumouni': 'not found',
 'université marc bloch': 'not found',
 'collège des bernardins': 'not found',
 'ana portilla est doctorante en sociologie à l école': 'not found',
 'université robert schuman': 'not found',
 'université paris-1 paris france': 'not found',
 'institut national de podologie': 'not found',
 'institut de chimie organique et analytique': 'https://ror.org/03ywn7d79',
 'university of paris 8 saint-denis cedex 02 france': 'not found',
 'institut convergences migrations': 'not found',
 'école normale supérieure': 'https://ror.org/04zmssz18',
 'universiteit nijmegen': 'not found',
 'universite de pau et des pays de l adour': 'https://ror.org/01frn9647',
 'brain institut': 'not found',
 'institut de recherche et documentation en economie de la santé': 'not found',
 'au département d italien de l université': 'not found',
 'maître de conférences-hdr à l université': 'not found',
 'université de chambéry': 'https://ror.org/04gqg1a07',
 'institut rayonnement matière de saclay': 'https://ror.org/00cch2r34',
 'university paris diderot': 'not found',
 'école polytechnique': 'https://ror.org/00szawm58',
 'doctorant à l institut': 'not found',
 'institut de biologie intégrative de la cellule': 'https://ror.org/01fftxe08',
 'laboratoires de recherche de l école': 'not found',
 'ethics ea 7446université': 'not found',
 'universitaires du septentrion': 'not found',
 'université de paris ouest nanterre la défense': 'not found',
 'école nationale supérieure d architecture de bretagne': 'not found',
 'senior fellow à l institut': 'not found',
 'france maître de conférences en psychologie université': 'not found',
 'institut d electronique et des systèmes': 'not found',
 'universitaires de france presses universitaires france': 'not found',
 'il est chercheur invité à l institut de sociologie de l université de neuchâtel et à l institut': 'not found',
 'institut godin': 'not found',
 'institut néel': 'https://ror.org/04dbzz632',
 'susan ball is senior lecturer in contemporary british civilisation at the university': 'not found',
 'université lyon 2': 'not found',
 'université paris ouest nanterre la défense 200 av': 'not found',
 'il est docteur en sociologie de l école': 'not found',
 'aux presses universitaires': 'not found',
 'maison rené ginouvès umr 7041 21 allée de l université': 'not found',
 'plateforme universitaire': 'not found',
 'universitaire72000 le mans': 'not found',
 'institut': 'https://ror.org/01dkyve95',
 'université paris diderot': 'not found',
 'université mcgill': 'not found',
 'umr 8533 cnrs   université': 'not found',
 'institut d histoire des représentations et des idées dans les modernités': 'not found',
 'savoirs et sociétés université': 'not found',
 'institut de génétique humaine 141 rue de la cardonille 34396 montpellier cedex 5': 'not found',
 'universite paris 8': 'https://ror.org/04wez5e68',
 'university of sorbonne paris north': 'https://ror.org/0199hds37',
 'universite paris 1 pantheon-sorbonnemaison des sciences économiques106-112 boulevard de l hôpital75647 paris cedex 13': 'not found',
 'université catholique de lille60 boulevard vauban59000 lille': 'not found',
 'institut du désert et des steppes': 'not found',
 'maître de conférences umr lavue université': 'not found',
 'university paris-est créteil': 'not found',
 'lunam université': 'not found',
 'universite paris 8 ufr de psychologie': 'not found',
 'université d evry-val-d essonneboulevard françois mitterrand91025 evry cedex': 'not found',
 'université jean monnetsite tréfilerie': 'not found',
 'institut de l ouest': 'https://ror.org/030ewzw66',
 'transferts critiques et dynamique des transferts critiques et dynamique université': 'not found',
 'université montesquieu': 'not found',
 'doctorante en études de genre et de sexualité   sociologie à l université': 'not found',
 'universities': 'https://ror.org/043rxf076',
 'institut marcel mauss': 'https://ror.org/02c5gbd66',
 'institut des matériaux de cergy-pontoise': 'not found',
 'university professor': 'not found',
 'docteur hdr en géopolitique de l institut': 'not found',
 'université paris 1 panthéon-sorbonne et chercheuse à l idhe': 'not found',
 'institut jean le rond d alembert': 'not found',
 'institut agro dijon': 'https://ror.org/03zek0r74',
 'institut pierre louis d epidémiologie et de santé publique': 'not found',
 'puis lors de son doctorat à l université de montréal et l université': 'not found',
 'école nationale des chartes': 'https://ror.org/013xvg556',
 'de la région île-de-france décernée par l institut': 'not found',
 'iae nancy school': 'not found',
 'institut de géographie': 'not found',
 'école centrale paris': 'not found',
 'university of paris 8 93526 saint-denis france': 'not found',
 'écoles': 'https://ror.org/042949r55',
 'de la jeunesse et des sports du kosovo école': 'not found',
 'benjamin fiorini est maître de conférences en droit privé et sciences criminelles à l université': 'not found',
 'école nationale supérieure d architecture paris val-de-seine crh': 'not found',
 '57045 metz cedexuniversité': 'not found',
 'maître de conférences en études sur la stratégie et la guerre à l institut français de géopolitique de l université': 'not found',
 'institut national de recherche en informatique et en automatique': 'https://ror.org/02kvxyf05',
 'institut français de géopolitique de l université paris-viii': 'not found',
 'universitaire': 'https://ror.org/03f099r71',
 'université paul-valéry montpellier 3': 'not found',
 'université paris 1-panthéon sorbonne': 'https://ror.org/002t25c44',
 'aix marseille université': 'https://ror.org/035xkbk20',
 'université françois-rabelais': 'not found',
 'institut élie cartan de lorraine': 'https://ror.org/04rvw8791',
 'university management lab': 'not found',
 'institut de recherche et coordination acoustique': 'https://ror.org/0121jnt59',
 'collège international de philosophie': 'not found',
 'cnrs-laga université paris 13 cnrs laga université': 'not found',
 'école centrale de marseille': 'https://ror.org/040baw385',
 'école nationale supérieure d architecture de paris la villette': 'not found',
 'univ': 'https://ror.org/015m7wh34',
 'laboratoire d acoustique de l université': 'not found',
 'university of paris ouest-nanterre 200 avenue de la republique 92001 nanterre cedex france': 'not found',
 'université libre de bruxelles': 'not found',
 'faculté d education de l université': 'not found',
 'institutions et dynamiques historiques de l economie': 'https://ror.org/03p76m698',
 'université paris-x nanterre': 'not found',
 'institut pierre renouvin 1': 'not found',
 'universitésite chênes 233': 'not found',
 'cresppa université': 'not found',
 'polina manko est diplômée de master en arts du spectacle vivant de l université': 'not found',
 'umr 8533 cnrs et université': 'not found',
 'université paris': 'https://ror.org/013cjyk83',
 'il est membre de l institut universitaire': 'not found',
 'universite paris 2': 'not found',
 'indiana university': 'not found',
 'université paris 13 sorbonne paris cité cnrs 93430 villetaneuse france': 'not found',
 'arscan -21 allée de l université': 'not found',
 'teikyo university': 'not found',
 'she is now an assistant professor of second language acquisition in the english department of université': 'not found',
 'institute and led': 'not found',
 'université d evry val d essonne': 'not found',
 'dvrc pôle universitaire': 'not found',
 'professeur d histoire-géographie affecté à l institut universitaire': 'not found',
 'université de paris ouest': 'not found',
 'collège universitaire': 'not found',
 'université de cologne': 'not found',
 'université de paris université de paris': 'not found',
 'cnrs -université paris 8 cnrs université': 'not found',
 'christine delory-momberger est professeure émérite en sciences de l éducation à l université': 'not found',
 'france  ethnologie préhistorique and centre de recherche et de documentation sur l océanie university': 'not found',
 'dhn-collège': 'not found',
 'univ-paris8': 'not found',
 'universitaire du pont de bois': 'not found',
 'école de droit': 'https://ror.org/02nwb8925',
 'de l université': 'https://ror.org/035hv2v80',
 'institut claude de préval': 'not found',
 'université michel de montaigne-bordeaux 3 et membre de l équipe de recherche mica': 'not found',
 'intermédiaires et consécration dans les univers': 'not found',
 'maître de conférences laboratoire lavue université': 'not found',
 'universud': 'not found',
 'université de nice sophia-antipolis': 'not found',
 'institut supérieur des beaux-arts de besançon': 'https://ror.org/02z87sy46',
 'école nationale supérieure de chimie et de physique de bordeaux': 'not found',
 'university of paris': 'https://ror.org/03xjwb503',
 'institut de recherche sur l antiquité et le moyen âge': 'https://ror.org/05jm22562',
 'institut français de l education': 'https://ror.org/04tmh0n51',
 'institut historique allemand': 'https://ror.org/02f1mqt91',
 '44312 nantes cedex 03université': 'not found',
 'france laboratoire laga umr 7539 cnrs université': 'not found',
 'institut supérieur des sciences agronomiques': 'https://ror.org/01s3fs709',
 'institut de recherche sur la fusion par confinement magnétique': 'https://ror.org/03hffat62',
 'univers de rennes': 'not found',
 'institut de sociologie de l université de neuchâtel et à l institut de recherche sociale de francfort': 'not found',
 'université d évry-val d essonne': 'not found',
 'labtop keivan djavadzadeh est doctorant en science politique à l université': 'not found',
 'université paris diderotufr ghss': 'not found',
 'martine beugnet est professeure en études visuelles à l ufr d études anglophones de l université': 'not found',
 'institut d histoire de la philosophie': 'not found',
 'laboratoire experice université': 'not found',
 'université campus joseph aiguier 31 chemin joseph aiguier 13402 marseille cedex 20': 'not found',
 'école nationale vétérinaire': 'https://ror.org/05q0ncs32',
 'henri desbois est maître de conférences en géographie à l université': 'not found',
 'université paris est créteil': 'https://ror.org/05ggc9x40',
 'université de cergy-pontoise 5 mail gay-lussac 95031 cergy-pontoise': 'not found',
 'institut de recherche juridique interdisciplinaire': 'https://ror.org/0576vz251',
 'institut de recherche sur les systèmes atomiques et moléculaires complexes': 'not found',
 'université paris-diderot': 'not found',
 'institut d ergologie': 'not found',
 'directeur du département d études arabes université': 'not found',
 'université paris 1 panthéon-sorbonne umr 7041 archéologie et sciences de l antiquité protohistoire égéenne archéologie et sciences de l antiquité protohistoire égéenne umr 7041 université paris 1 panthéon-sorbonne': 'not found',
 'lilpa université': 'not found',
 'école de sages-femmes baudelocque': 'not found',
 'institutions et des organisations': 'not found',
 'ufr stapsuniversité': 'not found',
 'université paris saclay': 'https://ror.org/03xjwb503',
 'european school': 'https://ror.org/05eyymj94',
 'institute of animal sciences': 'not found',
 'france normandie univ': 'not found',
 'université paris ouest': 'https://ror.org/013bkhk48',
 'devenu en 2016 une unité mixte de recherche associant le cnrs et l université': 'not found',
 'membre du bureau de cette université': 'not found',
 'université de paris-viii': 'https://ror.org/04wez5e68',
 'universitaire de psychologie': 'https://ror.org/03jrb0276',
 'université paul valéry montpellier 3route de mende 34199 montpellier cedex 5': 'not found',
 'institut de droit public': 'not found',
 'université paris-sorbonne': 'not found',
 'série de vidéos d actualité du droit pénal réalisées par les étudiants de l université': 'not found',
 'université paris laboratoire d économie dionysien-led': 'not found',
 'university of paris ouest-nanterre': 'not found',
 'il est actuellement doctorant contractuel en sciences de l information et de la communication à l université': 'not found',
 'il dirige l institut': 'not found',
 'laboratoire universitaire': 'https://ror.org/00y523k32',
 'institut de recherche mathématique de rennes': 'https://ror.org/05y76vp22',
 'institut de médecine intégrative et complémentaire': 'not found',
 'institut polytechnique de bordeaux': 'https://ror.org/054qv7y42',
 'emlyon business school': 'https://ror.org/009gmrj52',
 'universitaire expérience ressources culturelles éducation ea3971': 'not found',
 'ea 3456université': 'not found',
 'elle est professeure des universités à l institut': 'not found',
 'université de paris i panthéon sorbonne': 'not found',
 'school of political and social sciences': 'not found',
 'laboratoire interuniversitaire': 'not found',
 'ancien élève de l école normale supérieure de cachan et de l institut': 'not found',
 'institut de biologie et chimie des protéines': 'not found',
 'université': 'https://ror.org/03z6jp965',
 'montpellier business school': 'https://ror.org/037tw3m02',
 'céreq-eso université': 'not found',
 'institution paris 2015 questions théoriques': 'not found',
 'applica-tions umr 7539 université': 'not found',
 'institutions et sociétés': 'not found',
 'université 1': 'not found',
 'universitaire d angers': 'not found',
 'institut du droit de l espace': 'https://ror.org/047kfvz78',
 'avenue de l université': 'not found',
 'institut de psychologie': 'not found',
 'institut pasteur': 'not found',
 'université françois-rabelais de tours 3': 'not found',
 'université paris nord': 'not found',
 'institut lyfe': 'not found',
 'univ-paris-diderot': 'not found',
 'universitaire de besançon': 'https://ror.org/0084te143',
 'école primaire ruvoletto samantha université paris 8': 'not found',
 'institut denis poisson': 'https://ror.org/05djhd259',
 'universit e': 'not found',
 'presses universitaires': 'not found',
 'institut d histoire et de philosophie des sciences et des techniques': 'not found',
 'école universitaire': 'not found',
 'universitaire robert debré': 'not found',
 'université de prishtina et de l institut archéologique du kosovo': 'not found',
 'université paris doctorant en archéologie du monde égéen université paris': 'not found',
 'institut de chimie': 'https://ror.org/041yg4h55',
 'université paris ouest nanterre université paris ouest nanterre': 'not found',
 'université de franche-comté': 'not found',
 'west paris university': 'not found',
 'docteur hdr de l université': 'not found',
 'école nationale supérieure agronomique de toulouse': 'https://ror.org/03d5w9863',
 'enseignant en questions internationales à sciences po paris et à la paris school': 'not found',
 '21 all ee de l universit': 'not found',
 'university of paris 8 and paris 13': 'not found',
 'soutenue à l université': 'not found',
 'professeur invitée à el colegio de méxico professeur émérite de démographie université': 'not found',
 'institut neel': 'https://ror.org/04dbzz632',
 'enseignant au département culture et communication de l université': 'not found',
 'université paris-est-créteil': 'https://ror.org/05ggc9x40',
 'institut français napoli': 'not found',
 'institut d études européennes et membre honoraire de l institut universitaire': 'not found',
 'institut d etudes européennes': 'not found',
 'université de paris ufr ghes inégalités sociales': 'not found',
 'and member of the research group transcrit at the university': 'not found',
 'universitaire de tours': 'https://ror.org/00jpq0w62',
 'laga université': 'not found',
 'institut universitaire europe': 'not found',
 'université 35': 'not found',
 'université de lausanne and sorbonne université': 'not found',
 'université paris 1399': 'not found',
 'university of paris 8 93526 saint-denis': 'not found',
 'institut montaigne': 'not found',
 'institut de génétique moléculaire de montpellier': 'https://ror.org/02785qs39',
 'université degli studi di firenze': 'not found',
 'université paris 1 panthéon sorbonne': 'https://ror.org/002t25c44',
 'école nationale de la statistique et de l administration économique': 'https://ror.org/01fz7mn40',
 'université henri poincaré': 'not found',
 'universitaire expérience ressources culturelles éducation-experice': 'not found',
 'centre universitaire': 'https://ror.org/03078mv10',
 'brussels free university': 'not found',
 'université lumière': 'https://ror.org/03rth4p18',
 'institut d urbanisme de lyon': 'not found',
 'institut camille jordan': 'https://ror.org/01ekw7f87',
 'institut national des sciences de l univers': 'https://ror.org/04kdfz702',
 'université panthéon assas': 'https://ror.org/04qb2qm38',
 'université de paris-sud': 'not found',
 'institut des sciences humaines et sociales': 'https://ror.org/04b0z7q78',
 'université catholique de lille f-59000 lille france': 'not found',
 'france school': 'not found',
 'université paul-valéry': 'not found',
 'laboratoire de psychopathologie et de neuropsychologie universite': 'not found',
 'université paris l encyclopédie des guerres de jean-yves jouannais adrien chassain université': 'not found',
 'school of mechanical and manufacturing engineering': 'not found',
 'member of the president s board of this university': 'not found',
 'université de valenciennes et du hainaut-cambrésis': 'not found',
 'université paris 13 campus de bobigny 74 rue marcel cachin 93017 bobigny cedex': 'not found',
 'institut de recherche sur l education': 'https://ror.org/019qdtz78',
 'université de toulouse jean jaurès': 'not found',
 'université paris dauphine-psl': 'https://ror.org/052bz7812',
 'école doctorale de sciences sociales -université paris 8 courriel école doctorale de sciences sociales université paris 8 courriel': 'not found',
 'rennes university': 'not found',
 'university': 'https://ror.org/03hypw319',
 '1 paris 8 university': 'not found',
 'lyon catholic university': 'https://ror.org/01anhj553',
 'institut acte': 'https://ror.org/05hne2921',
 'instituto de biociências de botucatu': 'not found',
 'université nice sophia antipolis campus saint-jean-d angély': 'not found',
 'université paris 13': 'https://ror.org/0199hds37',
 'collège international de recherche biographique en éducation': 'not found',
 'université paris-ouest nanterre-la défense et membre du lavue': 'not found',
 'professeure de sociologie université': 'not found',
 'université paris 1': 'https://ror.org/002t25c44',
 'université laval': 'not found',
 'à l institut universitaire': 'not found',
 'samantha université': 'not found',
 'université de paris 1': 'not found',
 'institut télécom-télécom bretagne': 'not found',
 'professeure associée cornell university': 'not found',
 'université d évry-val d essonne paris-saclay': 'not found',
 'école doctorale d archéologie': 'not found',
 'université de naples': 'not found',
 'university paris liasd -university paris': 'not found',
 'universitaire de rennes': 'https://ror.org/05qec5a53',
 'université panthéon-assas': 'https://ror.org/04qb2qm38',
 'chercheuse en postdoctorat et cheffe de projet au sein du centre de recherche et de formation geode de l université': 'not found',
 'institut des sciences de l homme': 'not found',
 'université paris université': 'not found',
 'université paris 13 sorbonne paris cité': 'not found',
 'université européenne de bretagne': 'not found',
 'université d abidjan-cocody': 'not found',
 'doctorante en archéologie université': 'not found',
 'université paul valéry montpellier 3': 'not found',
 'universitaire des sciences de l homme': 'not found',
 'institut national d étude du travail et d orientation professionnelle': 'not found',

In [33]:
t_etab2 = t_etab1.loc[~t_etab1.id_rors.isna()]
t_etab3 = t_etab1.loc[t_etab1.id_rors.isna()]
t_etab2["rors"] = "https://ror.org/" + t_etab2.id_rors.astype(str)
t_etab3["rors"] = t_etab3.etab.map(dict_ror2.get)
t_etab3.loc[t_etab3.rors!="not found"].drop_duplicates("cleaned_etab")

/tmp/ipykernel_11041/4135308318.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_etab2["rors"] = "https://ror.org/" + t_etab2.id_rors.astype(str)
/tmp/ipykernel_11041/4135308318.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_etab3["rors"] = t_etab3.etab.map(dict_ror2.get)

,id,rank_id,etab,cleaned_etab,norm_name,id_rors,rors
0,halhal-03933378,0,institut national de recherches archéologiques...,institut national recherches archéologiques pr...,None,None,https://ror.org/04andmq85
2,halhal-03933378,7,université paris 1 panthéon-sorbonne,université paris 1 panthéon-sorbonne,None,None,https://ror.org/002t25c44
16,halhal-04579883,12,université,université,None,None,https://ror.org/03z6jp965
17,halhal-04579883,12,aix marseille université,aix marseille université,None,None,https://ror.org/035xkbk20
22,nnt2006troy0017,15,institut supérieur de mécanique de paris,institut supérieur mécanique paris,None,None,https://ror.org/04dtfqt68
...,...,...,...,...,...,...,...
115447,doi10.3917/rfse.013.0241,54956,université paris ouest nanterre-la défense,université paris ouest nanterre-la défense,None,None,https://ror.org/013bkhk48
117277,halhal-04672512,55846,institut national de recherche et de sécurité,institut national recherche et sécurité,None,None,https://ror.org/01dg85j68
117583,doi10.3917/arch.221.0153,56010,école normale supérieure-psl,école normale supérieure-psl,None,None,https://ror.org/05a0dhs15
118053,halhal-04484125,56250,institut fresnel,institut fresnel,None,None,https://ror.org/03br1wy20
118175,doi10.4000/pallas.19740,56300,université paris 1-panthéon sorbonne,université paris 1-panthéon sorbonne,None,None,https://ror.org/002t25c44

In [41]:
df_allrors = pd.concat([t_etab2[["id","rank_id","rors"]], t_etab3[["id","rank_id","rors"]]])

df_adfr["rors"] = df_adfr.rank_id.map(dict(zip(df_allrors.rank_id, df_allrors.rors)))
df_umr = df_adfr.loc[df_adfr.name_umr!=""]
df_umr["umr"] = df_umr.name_umr.str.split("|")
df_umr1 = df_umr[["id","rank_id","umr"]].explode("umr").reset_index().drop(columns=["index"])
df_umr1["umr_id"] = df_umr1.index.astype(str)
df_umr1

/tmp/ipykernel_11041/477849833.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_umr["umr"] = df_umr.name_umr.str.split("|")

                    id rank_id      umr umr_id
0      halhal-03933378       1  umr7324      0
1      halhal-03933378       1  umr6173      1
2      halhal-03933378       7  umr7041      2
3      halhal-03895949       8  umr7041      3
4      halhal-01789653       9   ea1572      4
...                ...     ...      ...    ...
34903  halhal-04366816   56310    ea827  34903
34904  halhal-02120667   56313  umr7041  34904
34905  halhal-02120667   56314  umr5600  34905
34906  halhal-02120667   56315  umr7266  34906
34907  halhal-01964707   56316  umr7023  34907

[34908 rows x 4 columns]

In [50]:
list_umr = list(set([x for x in df_umr1.umr]))
print(len(list_umr))
dict_ror3 = {}
for m, umr in tqdm.tqdm(enumerate(list_umr), total = len(list_umr)):
    label_umr = umr.replace("umr","umr ").replace("ea","ea ").replace("ums", "ums ")
    
    response = requests.get(ROR_API_ENDPOINT + '?' + f'query="{label_umr}"' + "&filter=country.country_code:fr").json()
    if response["number_of_results"] > 1 :
        for n, x in enumerate(response["items"]):
            if 'education' in x["types"] :
                datas = response["items"][n]
                rors = datas["id"]
    elif response["number_of_results"] == 1 :
        datas = response["items"][0]
        rors = datas["id"]
    else:
         rors = "not found"
    dict_ror3[umr] = rors
    #print(cleaned_etab, rors)

1120

100%|██████████| 1120/1120 [02:27<00:00,  7.60it/s]

In [91]:
file_path = BUCKET_OUT + "/" + "/Data_bso/referentiels/fr-esr-repertoire-national-structures-recherche-historique-annuel.csv"
with fs.open(file_path) as csvin:
    umr_histo = pd.read_csv(csvin, sep =";")
    

file_path = BUCKET_OUT + "/" + "/Data_bso/referentiels/fr-esr-structures-recherche-publiques-actives.csv"
with fs.open(file_path) as csvin:
    umr = pd.read_csv(csvin, sep =";")
    
umr1 = umr.loc[~umr.label_numero.isna()]
umr1.loc[umr1.label_numero.str.contains("EA 4178")]
umr_histo1 = umr_histo.loc[~umr_histo["Label numéro"].isna()]
umr_histo1.loc[(umr_histo1["Label numéro"].str.contains("UMR 8608"))&(umr_histo1["Année"]==umr_histo1["Année"].max())].iloc[0]

Année                                                                                              2017
Numéro national de structure                                                                 199812935Y
Label numéro                                                                          UMR 8608,UMR 8608
Tutelles                                              Centre national de la recherche scientifique,U...
Sigles des tutelles                                                                                CNRS
SIRET des tutelles                                                                                  NaN
UAI des tutelles                                                                      0753639Y,0911101C
Code de type de tutelle                                                                       EPST,UNIV
Type de tutelle                                       Établissement public scientifique et technolog...
Code de nature de tutelle                                                                           6,6
Nature de tutelle                                           Établissement tutelle,Établissement tutelle
Numéro de structure parent                                                                          NaN
Numéro de structure enfant                                                                          NaN
Prénom du responsable                                                                            Faiçal
Nom du responsable                                                                               AZAIEZ
Titre du responsable                                                                          Directeur
Email du responsable                                                                                NaN
Code domaine scientifique                                                                           NaN
Domaine scientifique                                                                                NaN
Code panel ERC                                                                                      NaN
Panel ERC                                                                                           NaN
Code thème de recherche                                                                             NaN
Thème de recherche                                                                                  NaN
Lien répertoire national de structure de recherche    https://data.enseignementsup-recherche.gouv.fr...
Lien structures de recherche actives                  https://data.enseignementsup-recherche.gouv.fr...
Name: 55826, dtype: object

In [105]:
file_path = BUCKET_OUT + "/" + "/Data_bso/referentiels/fr-esr-repertoire-national-structures-recherche.csv"
with fs.open(file_path) as csvin:
    rnsr = pd.read_csv(csvin, sep =";")

rnsr.loc[rnsr.numero_national_de_structure=="202023524M"]

,numero_national_de_structure,libelle,sigle,etat,annee_de_creation,annee_de_fermeture,type_de_structure,code_de_type_de_structure,code_de_niveau_de_structure,numero_de_structure_successeur,code_de_type_de_succession,type_de_succession,annee_de_succession
11805,202023524M,Laboratoire de physique des 2 infinis – Irène ...,IJCLab,Active,2020.0,NaN,Unité mixte,22,2,NaN,NaN,NaN,NaN

In [93]:
print(len([x for x in dict_ror3 if dict_ror3[x]=="not found"]))

737

In [98]:
for umr in dict_ror3:
    if dict_ror3[umr] == "not found":
        print("######", umr)
        label_umr = umr.replace("umr_","umr").replace("umr","umr ").replace("ea","ea ").replace("ums", "ums ").replace("  ", " ")
        try:
            libelle = umr1.libelle.loc[umr1.label_numero.str.lower().str.contains(label_umr)].iloc[0]
            commune = umr1.commune.loc[umr1.label_numero.str.lower().str.contains(label_umr)].iloc[0]
        except:
            libelle = "unknown"
            commune = "unknown"
        if libelle != "unknown":
            libelle= libelle.replace("&","and")
            print(libelle)
            response = requests.get(ROR_API_ENDPOINT + '?' + f'query="{libelle.lower()}"' + "&filter=country.country_code:fr").json()
            if response["number_of_results"] > 1 :
                for n, x in enumerate(response["items"]):
                    if 'education' in x["types"] :
                        datas = response["items"][n]
                        rors = datas["id"]
                        dict_ror3[umr] = rors
            elif response["number_of_results"] == 1 :
                datas = response["items"][0]
                rors = datas["id"]
                dict_ror3[umr] = rors
            else:
                 rors = "not found"

###### ea4178
CENTRE PLURIDISCIPLINAIRE TEXTES ET CULTURES - UR 4178
###### umr8608
###### umr8109
###### ea7464
Architecture Territoire Environnement Normandie
###### umr7249
Institut Fresnel Marseille
###### umr9190
MARine Biodiversity, Exploitation and Conservation
###### eau33000
###### umr154
###### umr5313
Laboratoire d'Economie Appliquée de Grenoble
###### umr_8225
###### ea2445
###### umr1326
Laboratoire Interdisciplinaire Sciences, Innovations, Sociétés
###### umr5805
Environnements et paléoenvironnements océaniques et continentaux
###### ea4009
###### umr1397
LABORATOIRE DE RECHERCHE EN CARDIOVASCULAIRE, METABOLISME, DIABETOLOGIE ET NUTRITION
###### ea7425
###### umr6607
Laboratoire de Thermique et Énergie de Nantes
###### umr0985
Dynamique et durabilité des écosystèmes : de la source à l’océan
###### ea3897
RECHERCHES ET ETUDES SUR LES CHOIX INDUSTRIELS, TECHNOLOGIQUES ET SCIENTIFIQUES
###### umr_7164
###### umr6204
###### ea3214
###### ea7390
###### ea4306
###### umr8179
###### umr5605
###### eau34300
###### umr9220
Ecologie marine tropicale dans les Océans Pacifique et Indien
###### umr7064
Centre méditerranée de sociologie, de science politique et d'histoire
###### ea4333
THEMIS UNIVERSITE DU MANS
###### umr6574
###### umr8044
Centre d'étude des mouvements sociaux
###### umr8554
Laboratoire de sciences cognitives et psycholinguistique
###### ea3263
LABORATOIRE MANCEAU DE MATHEMATIQUES
###### umr7183
###### ea608
GROUPE DE RECHERCHE SUR LES ENJEUX DE LA COMMUNICATION
###### umr1459
###### umr5292
Centre de Recherche en Neurosciences de Lyon
###### ea4461
Ecole de droit de Sciences Po
###### ums104
###### ea375
###### ea4512
###### ea4601
PATRIMOINE LITTÉRATURE HISTOIRE
###### umr3495
Modèles et simulations pour l'Architecture et le Patrimoine
###### umr1202
Biodiversité, Gènes et Communautés
###### ea4385
LABORATOIRE D'ÉTUDES ROMANES
###### umr5602
GEOGRAPHIE DE L'ENVIRONNEMENT
###### umr7013
UMR 7013 Institut Denis Poisson
###### umr7031
Laboratoire de mécanique et d'acoustique
###### umr7360
Laboratoire Interdisciplinaire des Environnements Continentaux
###### ea4314
GROUPE DE RECHERCHE IDENTITÉS ET CULTURES - UR 4314
###### ea1441
###### umr_7586
###### ea3804
Centre de REcherche en STIC
###### ea4509
SENS, TEXTE, INFORMATIQUE, HISTOIRE
###### umr7353
###### ea3159
###### ea4429
###### ea7339
DISPOSITIFS D'INFORMATION ET DE COMMUNICATION À L'ÈRE NUMÉRIQUE PARIS ILE DE FRANCE
###### ea3811
HELLENISATION ET ROMANISATION DANS LE MONDE ANTIQUE : IDENTITES ET PHENOMENES INTERCULTURELS
###### ums1797
###### ea7322
Fabrique du littéraire
###### ea4281
###### ea7374
LABORATOIRE D'URBANISME
###### ea3276
###### umr123
Rongeurs Sauvages, Risques Sanitaires et Gestion des Populations
###### ea4163
###### umr7069
Laboratoire interdisciplinaire en études culturelles (UMR 7069)
###### umr5145
###### ea1697
LABORATOIRE DE PSYCHOLOGIE DE LA SOCIALISATION - DEVELOPPEMENT ET TRAVAIL
###### ea4701
###### umr8185
Médiations, Sciences des lieux, Sciences des liens
###### ea353
Laboratoire d'Institut Français de Géopolitique
###### ea7287
###### ea3272
###### ea4246
###### umr1131
Santé de la Vigne et Qualité du Vin (UMR_A 1131)
###### umr66
LABORATOIRE D'ACOUSTIQUE DE L'UNIVERSITE DU MANS
###### ea741
Centre d'Etudes Ibériques et Ibéro-américaines
###### umr7063
Institut Terre Environnement Strasbourg
###### umr_8236
###### umr6054
###### umr_7219
###### ea739
Conception de Systèmes Mécaniques et Robotiques
###### umr7295
CENTRE DE RECHERCHES SUR LA COGNITION ET L'APPRENTISSAGE
###### ea4223
CENTRE D'ETUDES ET DE RECHERCHES SUR L'ESPACE GERMANOPHONE
###### umr5052
###### umr7304
Centre Gilles-Gaston GRANGER
###### ea3423
CENTRE DE RECHERCHE SUR LES POÉTIQUES DU XIXÈME SCIÈCLE
###### umr0951
Innovation et Développement dans l'Agriculture et l'Alimentation
###### umr1458
Gestion de l'eau, acteurs et usages
###### umr7112
###### umr1518
Sociétés, acteurs, gouvernement en Europe (UMR 7363)
###### umr6570
###### ea1577
LES MONDES ALLEMANDS : REGIONS, HISTOIRE, CULTURES, SOCIETES
###### umr8034
###### ea4430
###### umr6222
###### ea1161
###### ea3003
###### umr_8586
###### umr5252
###### umr5199
De la Préhistoire à l'Actuel : Culture, Environnement et Anthropologie
###### ea3391
LABORATOIRE D'ECONOMIE DIONYSIEN
###### ea3918
###### ea4254
###### ea4116
SAVOIRS ET PRATIQUES, DU MOYEN AGE À L'ÉPOQUE CONTEMPORAINE
###### umr7656
###### ea439
CENTRE DE RECHERCHE SUR LES MONDES ANGLOPHONES
###### umr_7598
###### ea3648
###### umr7236
###### umr5040
###### ums3598
###### umr7334
Institut des Matériaux, de Microélectronique et des Nanosciences de Provence
###### umr228
###### umr8031
###### umr8110
###### ea4004
Cognitions humaine et artificielle (CHArt)
###### ea4112
ULR 4112 - LSMRC - Lille School of Management Research Center
###### ea2290
###### ea3413
###### umr_8243
###### umr171
###### ea7492
###### umr6578
###### ea1803
LABORATOIRE DES SCIENCES DE L'INFORMATION ET DE LA COMMUNICATION
###### umr8628
Laboratoire de mathématiques d'Orsay
###### ums622
###### ea3816
###### umr7262
LABORATOIRE DE PALEONTOLOGIE, EVOLUTION, PALEOECOSYSTEMES, PALEOPRIMATOLOGIE
###### umr7030
Laboratoire d'Informatique de Paris-Nord
###### umr7285
INSTITUT DE CHIMIE DES MILIEUX ET MATERIAUX DE POITIERS
###### ea1764
###### umr5316
LittandArts
###### ea7529
Formation et apprentissages professionnels
###### umr_8001
###### ea3096
LABORATOIRE DE GÉNIE INFORMATIQUE, DE PRODUCTION ET DE MAINTENANCE
###### umr1041
Centre d'économie et de sociologie appliquées à l'agriculture et aux espaces ruraux
###### umr7599
###### umr1101
Laboratoire de traitement de l'information médicale
###### umr7198
Institut Jean Lamour
###### umr9004
Institut de Recherche en Infectiologie de Montpellier
###### ea1484
###### ea2114
Psychologie des Âges de la Vie et Adaptation
###### ea4275
BIOSTATISTIQUE, PHARMACOEPIDEMIOLOGIE ET MESURES SUBJECTIVES EN SANTE
###### umr1122
###### ea4305
###### ea740
INSTITUT DE RECHERCHE INTERSITE ETUDES CULTURELLES
###### umr7020
Laboratoire d'Informatique et des Systèmes
###### ea3350
ANALYSE COMPAREE DES POUVOIRS
###### umr6588
###### ea7326
###### ea4455
Cultures, Environnements, Arctique, Représentations, Climat
###### ea4671
###### umr7535
###### umr4574
UMRU 4574 - SCIENCES, PHILOSOPHIE, HUMANITÉS
###### ea7474
Dynamique du langage in situ
###### ea3043
LABORATOIRE DE TRAITEMENT ET TRANSPORT DE L'INFORMATION
###### umr8219
###### umr3299
###### ea_4434
###### ea4692
Centre d'Etude et de Recherche sur les Emplois et la Professionnalisation
###### umr8067
Laboratoire de Biologie des organismes et des écosystèmes aquatiques
###### ea4298
###### ea7332
CENTRE DE LINGUISTIQUE EN SORBONNE
###### ea2336
###### umrt9403
###### umr7171
###### umr7290
###### ea1059
###### ea7348
Management des organisations de santé
###### ea4513
CENTRE DE RECHERCHES EUROPES-EURASIE
###### umr6565
###### ea1572
ESTHÉTIQUE, MUSICOLOGIE, DANSE ET CRÉATIONS MUSICALES
###### umr_7110
###### umr7225
Institut du Cerveau
###### umr8007
LABORATOIRE D'ECONOMIE DE DAUPHINE
###### umr7635
Centre de Mise en Forme des Matériaux
###### ea3459
###### umr5218
Laboratoire d'intégration du matériau au système
###### ea3812
###### umr8536
###### umr6629
LABORATOIRE DE MATHEMATIQUES JEAN LERAY
###### umr8029
Laboratoire des Systèmes et Applications des Technologies de l'Information et de l'Energie
###### ums3603
Structuration et Internationalisation des SHS
###### umr8523
UMR 8523 - PHLAM  - Physique des lasers, atomes et molécules
###### ea4145
LABORATOIRE INTERUNIVERSITAIRE DE PSYCHOLOGIE. PERSONNALITE, COGNITION, CHANGEMENT SOCIAL EA4145
###### ea3742
LABORATOIRE SPORT ET ENVIRONNEMENT SOCIAL
###### umr6004
Laboratoire des Sciences du Numérique de Nantes
###### umr7022
###### ea2310
###### umr6173
###### ea891
###### umr5594
###### ea4272
###### eau91405
###### umr9958
###### umr8051
Equipes Traitement de l'Information et Systèmes
###### umr7622
###### umr7501
Institut de recherche mathématique avancée (UMR 7501)
###### ea 4010
###### ea_4410
###### umr_8111
###### umr5206
TRIANGLE : ACTION, DISCOURS, PENSEE POLITIQUE ET ECONOMIQUE
###### ea1569
TRANSFERTS CRITIQUES ANGLOPHONES (TransCrit)
###### umr6242
###### ums3113
Institut Universitaire Européen de la Mer
###### umr5022
LABORATOIRE D'ETUDE DE L'APPRENTISSAGE ET DU DEVELOPPEMENT - UMR 5022
###### umr5136
France, Amériques, Espagne, Sociétés, Pouvoirs, Acteurs
###### ea2517
###### umr112
Dynamique des Génomes et Adaptation Microbienne
###### umr8547
Pays germaniques (Histoire, Culture, Philosophie) - Transferts Culturels / Archives Husserl de Paris
###### umr6310
LABORATOIRE DE LINGUISTIQUE DE NANTES
###### umr7055
Préhistoire et Technologie
###### umr_8173
###### ea3795
Groupe d'Etude des Géomatériaux et Environnements Naturels, Anthropiques et Archéologiques
###### ea2303
###### umr119
Biologie de la reproduction, environnement, épigénétique et développement
###### ea4571
Education, Cultures, Politiques
###### umr8188
CRIL - Centre de Recherche en Informatique de Lens
###### ea1588
###### umr5569
###### ums2553
###### umr7146
###### umr0042
Centre alpin de recherche sur les réseaux trophiques des écosystèmes limniques
###### ea4187
###### ea4649
###### umr8112
###### ea4702
LABORATOIRE D’ÉCONOMIE ROUEN NORMANDIE
###### umr6130
###### umr1248
AGroécologie, Innovations, teRritoires
###### ea7505
Education, Ethique, Santé
###### ea160
INSTITUT DE RECHERCHE EN PROPRIETE INTELLECTUELLE HENRI DES BOIS
###### ea_3967
###### umr7194
Histoire Naturelle des Humanités Préhistoriques
###### umr6526
###### ea2529
###### ea3412
LABORATOIRE EDUCATIONS ET PROMOTION DE LA SANTÉ
###### ea1285
Laboratoire de Psychologie : Cognition, Comportement, Communication
###### umr1091
###### ea4343
###### umr5059
###### umr8026
UMR 8026 - CERAPS - Centre d'Etudes et de Recherches Administratives, Politiques et Sociales
###### umr6221
###### umr7012
###### umr1135
Centre d'Economie de l'Environnement - Montpellier
###### ea3119
Centre d'étude des discours, images, textes, écrits et communications
###### umr8018
###### ea7454
Centre Interdisciplinaire de Recherche Normand en Education et Formation
###### ea4232
###### umr1110
Montpellier Interdisciplinary center on Sustainable Agri-food systems - social and nutritional sciences
###### umr195
###### umr5197
###### umr5269
Laboratoire de Génie Electrique de Grenoble
###### umr7176
###### umr7130
Laboratoire d'anthropologie sociale
###### umr7116
Centre de sociologie des organisations
###### umr7367
###### umr7369
Matrice Extracellulaire et DYnamique Cellulaire
###### ea7278
###### umr6027
Institut de Recherche Dupuy de Lôme
###### ea4428
###### umr1347
AGROECOLOGIE - UMR 1347
###### ea4383
LABORATOIRE D'INTELLIGENCE ARTIFICIELLE ET SÉMANTIQUE DES DONNÉES
###### ea4160
###### ea4162
###### ea7318
INSTITUT DE RECHERCHE SUR L'EDUCATION - UR 7318
###### umr6569
###### umr9993
###### ea7338
Centre de recherche pluridisciplinaire en Lettres, Langues, Sciences Humaines et des Sociétés
###### umr3320
Laboratoire Interdisciplinaire pour la Sociologie Economique
###### umr7244
Laboratoire de Chimie bioorganique, biophysique et biomatériaux pour la santé
###### umr_7583
###### umr6113
###### umr8502
Laboratoire de Physique des Solides
###### umr8242
###### ea7458
Laboratoire de Psychologie: Dynamiques Relationnelles Et Processus Identitaires - UR 7458
###### ea4047
###### umr6057
###### umr9931
###### umr7247
Physiologie de la reproduction et des comportements
###### eac4459
###### umr7135
###### umr5245
###### ea4139
###### ea3457
###### umr5603
###### ea4277
Identité Culturelle, Textes et Théatralité
###### ea3206
###### ea3820
###### umr7275
Institut de pharmacologie moléculaire et cellulaire
###### ums841
###### umr7243
Laboratoire d'analyse et modélisation de systèmes pour l'aide à la décision
###### umr1027
###### umr5815
###### ea1207
UR 1207 PHYSIOLOGIE, ECOLOGIE, ENVIRONNEMENT
###### umr8238
Laboratoire d'études sur le genre et la sexualité
###### umr7048
Centre de recherches politiques de Sciences Po
###### ea7446
###### umr6297
DROIT ET CHANGEMENT SOCIAL
###### ea3389
###### ea7469
###### umr6636
###### umr1302
Structures et marchés agricoles, ressources et territoires
###### umr242
Institut d'écologie et des sciences de l'environnement de Paris
###### ea7403
###### ea3380
###### ea7496
###### umr8244
Institut d'histoire du temps présent
###### umr6265
###### umr1221
Laboratoire d'étude des interactions sol - agrosystème - hydrosystème
###### umr6306
###### umr6232
###### umr5015
###### ea1163
CENTRE DE RECHERCHES EN HISTOIRE INTERNATIONALE ET ATLANTIQUE- CRHIA
###### umr0356
###### ea4360
###### ea2356
###### ea4154
LABORATOIRE DE RECHERCHE EN AUDIOVISUEL-SAVOIRS, PRAXIS ET POÏTIQUES EN ART
###### umr0203
Biologie Fonctionnelle, Insectes et Interactions
###### ea2450
###### umr7118
Analyse et Traitement Informatique de la Langue Française
###### umr_8109
###### umr6166
###### ea3958
###### umr1092
ANTI-INFECTIEUX : SUPPORTS MOLÉCULAIRES DES RÉSISTANCES ET INNOVATIONS THÉRAPEUTIQUES
###### ea1589
###### eam5
###### umrd216
###### ea4420
DISPOSITIFS D'INFORMATION ET DE COMMUNICATION À L'ÈRE NUMÉRIQUE PARIS ILE DE FRANCE
###### umr7647
Laboratoire de physique des interfaces et des couches minces
###### ea814
Institut Clément Ader
###### ea609
LINGUISTIQUE ET DIDACTIQUE DES LANGUES ETRANGERES ET MATERNELLES
###### ea7304
###### umr204
###### ea1410
###### umr0782
Paris-Saclay Food and Bioproduct Engineering Research Unit
###### ea3279
Centre d'Etudes et de Recherche sur les Services de Santé et la Qualité de Vie
###### ea969
NORMANDIE INNOVATION MANAGEMENT ENTREPRISE CONSOMMATION
###### umr6012
###### umr8552
Laboratoire Kastler Brossel
###### ums3657
###### eau75014
###### ea7352
Détection, évaluation, gestion des risques chroniques et émergents
###### ea4700
###### umr1273
TERRITOIRES
###### umr6123
###### ea1038
###### ea7493
EA 7493 Equipe de Recherche Contextes et Acteurs de l'Education
###### umr2558
###### ea801
CENTRE FOR ANGLOPHONE STUDIES
###### umr1402
Ecologie fonctionnelle et écotoxicologie des agroécosystèmes
###### ea3562
###### umr5607
UMR 5607 - Ausonius INSTITUT DE RECHERCHE SUR L'ANTIQUITE ET LE MOYEN AGE
###### umr0729
Mathématiques, informatique et statistique pour l'environnement et l'agronomie
###### ums305
###### umr853
Laboratoire de météorologie dynamique
###### umr_8155
###### umr6307
###### ea3649
###### umr7306
Institut de Recherches Asiatiques
###### ums3623
Centre de microcaractérisation Raimond Castaing
###### ea4235
###### umr1410
Centre de recherche et d'enseignement des géosciences de l'environnement
###### ea7373
Laboratoire Interdisciplinaire d'études du Politique Hannah Arendt
###### umr8582
Groupe Sociétés, Religions, Laicités.
###### ea4625
CENTRE DE RECHERCHE EN ECONOMIE DE GRENOBLE
###### ea3388
CENTRE D'ETUDES SUR LES MEDIAS, LES TECHNOLOGIES ET L'INTERNATIONALISATION
###### ea3794
###### umr8077
Centre d'études sud asiatiques et himalayennes
###### umr5563
Géosciences Environnement Toulouse
###### ea1573
SCÈNES DU MONDE, CRÉATION, SAVOIRS CRITIQUES
###### umr5620
###### ea437
Equipe de recherche sur l'utilisation des données individuelles en lien avec la théorie économique
###### umr1215
Laboratoire d'Economie Appliquée de Grenoble
###### umr5222
###### ea2129
###### ea7476
Laboratoire des dynamiques sociales
###### ea3273
###### ums2572
###### umr5125
###### umr5219
Institut de Mathématiques de Toulouse
###### umr7221
Physiologie Moléculaire et Adaptation
###### ea4008
LABORATOIRE D'ÉTUDES ET DE RECHERCHES SUR LES LOGIQUES CONTEMPORAINES DE LA PHILOSOPHIE
###### umr7502
Institut Elie Cartan de Lorraine
###### ums2809
LUTIN
###### umr6591
###### umr5198
###### umr7061
Perception, Représentations, Image, Son, Musique
###### ea4180
###### ea7447
Recherches en innovation sociale par le Design
###### umr5255
Institut des Sciences Moléculaires
###### umr7075
###### umr5275
Institut des Sciences de la Terre
###### umr6073
###### umr8087
Patrimoines locaux, environnement et globalisation
###### ea3819
###### ea4459
###### ea6301
INTERACTIONS, TRANSFERTS, RUPTURES ARTISITIQUES ET CULTURELLES
###### umr6621
###### umr6258
###### umr1295
Centre d'Epidémiologie et de Recherche en santé des POPulations de Toulouse
###### umr1427
Institut de recherche Interdisciplinaire en Sociologie, Economie et Science Politique (IRISSO)
###### umr5060
###### umr7217
Centre de Recherches Sociologiques et Politiques de Paris - CRESPPA
###### umr1415
Toulouse School of Economics - Research (TSE-Recherche)
###### umr8097
Centre Maurice Halbwachs
###### umr5193
Laboratoire interdisciplinaire Solidarités, Sociétés, Territoires
###### ea7521
CENTRE DE RECHERCHES APPLIQUEES A LA GESTION
###### ea3713
###### umr7305
###### ea4262
###### umr1225
Interactions hôtes-agents pathogènes
###### umr151
Laboratoire d'Etudes Rurales
###### umr5262
###### umr113
Centre d'Economie de l'Environnement - Montpellier
###### umr1334
Institut Amélioration Génétique et Adaptation des Plantes méditerranéennes et Tropicales
###### umr_7154
###### umr9006
Institut photovoltaïque d'Ile-de-France
###### umr5298
Laboratoire Photonique, Numérique, Nanosciences
###### umr8177
Laboratoire d'anthropologie politique
###### ea6300
Laboratoire d'Informatique Fondamentale et Appliquée de Tours
###### umr7
Archéologie et Histoire Ancienne : Méditerranée et Europe (UMR 7044)
###### umr7234
Centre de recherche en économie et gestion de Paris Nord
###### ea4007
LA SECTION CLINIQUE
###### umr5510
Matériaux : Ingénierie et Science
###### ea_7335
###### ea3059
Laboratoire d'Analyse des Signaux et des Processus Industriels
###### umr7538
Laboratoire de Physique des Lasers
###### umr5474
###### umr7301
MIGRATIONS INTERNATIONALES, ESPACES ET SOCIETES
###### umr6634
Groupe de Physique des Matériaux
###### umr8091
###### umr8529
UMR 8529 - IRHIS -  Institut de Recherches Historiques du Septentrion
###### ea4414
###### ea4010
ARTS DES IMAGES ET ART CONTEMPORAIN
###### ea7504
Arts/Langues : Transitions et Relations
###### ea1198
###### umr8239
Centre d'études européennes et de politique comparée
###### ea4424
CENTRE DE RECHERCHES INTERDISCIPLINAIRES EN SCIENCES HUMAINES ET SOCIALES DE MONTPELLIER
###### umr6139
LABORATOIRE DE MATHÉMATIQUES NICOLAS ORESME
###### ea2931
###### umr7111
###### ea1384
###### ea2468
###### ea3436
###### ea4395
Lettres, Idées, Savoirs
###### umr9016
Temps, Mondes, Sociétés
###### umr7268
Anthropologie bio-culturelle, Droit, Ethique et Santé
###### ea1060
###### ums830
###### ea3002
IDENTITES , TERRITOIRES, EXPRESSIONS, MOBILITES
###### umr9023
MODELISATION ALEATOIRE DE PARIS X
###### umr6502
INSTITUT DES MATERIAUX DE NANTES JEAN ROUXEL
###### ea7452
###### umr8623
###### umr8144
###### umr8561
###### umr_7592
###### ea4224
###### ea965
###### umr5095
Institut de Biochimie et Génétique Cellulaires
###### ea3831
GROUPE DE RECHERCHE D'HISTOIRE
###### umrt9406
###### ea4387
###### ea370
LANGAGES, LITTÉRATURES, SOCIÉTÉS. ÉTUDES TRANSFRONTALIÈRES ET INTERNATIONALES
###### umr7192
Proche-Orient, Caucase : langues, archéologie, cultures
###### ea7437
###### ums3278
###### ea3381
LABORATOIRE DE SOCIOLOGIE JURIDIQUE
###### ea3971
Laboratoire de recherche Interdisciplinaire sur les Socialisations, les Marges, l'Éducation et l'Expérience
###### ea3047
INSTITUT DE RECHERCHE EN DROIT DES AFFAIRES
###### umr5295
Institut de mécanique et d'ingénierie de Bordeaux
###### umr1210
###### ea7419
###### ums3116
Observatoire des Sciences de l'Univers en région Centre-Val de Loire
###### ea3311
Centre de Recherche Interdisciplinaire sur les Modèles Esthétiques et Littéraires
###### umr8035
###### umr8643
###### ea2474
LAB IAE Paris Sorbonne
###### umr6059
###### umr8138
Sorbonne, identités, relations internationales et civilisations de l’Europe
###### ea-3649
###### umr9000
Territoires, Environnement, Télédétection et Information Spatiale
###### ea7507
Performance, Santé, Métrologie, Société
###### umr985
###### umr6590
ESPACES ET SOCIETES

In [117]:
print(len([x for x in dict_ror3 if dict_ror3[x]!="not found"]))
df_umr1["rors"] = df_umr1.umr.map(dict_ror3.get)
df_umr2 = df_umr1.loc[df_umr1.rors!="not found"]
df_adfr["umr_ror"] = df_adfr.rank_id.map(dict(zip(df_umr2.rank_id, df_umr2.rors)).get)
pd.concat([df_adfr[["id","rank_id","rors"]], df_umr2[["id","rank_id","rors"]]]).drop_duplicates()

575

                    id rank_id                       rors
0      halhal-03933378       0  https://ror.org/04andmq85
1      halhal-03933378       1  https://ror.org/02wwzvj46
2      halhal-03933378       2                        NaN
3      halhal-03933378       3                        NaN
4      halhal-03933378       4                        NaN
...                ...     ...                        ...
34903  halhal-04366816   56310  https://ror.org/01bxfc994
34904  halhal-02120667   56313  https://ror.org/00wx1mx58
34905  halhal-02120667   56314  https://ror.org/0256r1e04
34906  halhal-02120667   56315  https://ror.org/00r8amq78
34907  halhal-01964707   56316  https://ror.org/00nrven85

[76450 rows x 3 columns]

In [ ]:
#récupéré sur Le Chat via la demande suivante : how can i detect unstructured address in text

nlp = spacy.load("fr_core_news_md")

for index, row in df_frwithoutumr.head(20).iterrows():
    print("######", row.address)
    doc = nlp(row.address)
    for ent in doc.ents:
        #print(ent.text)
        ent.
        if ent.label_ == "ORG" or ent.label_ == "LOC":
            print(ent.text)

# Les institutions non françaises

In [ ]:
df_nofr = df_ad.loc[~(df_ad.address.str.lower().str.contains("france|paris"))].reset_index().drop(columns=["index"])
df_nofr#.loc[~df_nofr.affiliation.isna()]

In [ ]:
for

In [ ]:
key ='École doctorale Pratiques et théories du sens'
status_response = requests.get(ROR_API_ENDPOINT + '?' + f'query="{key}"').json()
status_response

In [ ]:
dict_ror2 = {}
for m, a in enumerate(df_ad2.address.unique()[0:10]):
    row_id = m
    a_split = re.sub(r"[;,\.]", ";", a).split(";")
    nom_univ = re.sub(r"\[.*\]", "", a_split[0]).strip().replace("&egrave;", "è").replace("&", "%26%"). lower()
    #print(nom_univ)
    #key ='École doctorale Pratiques et théories du sens'
    
    try:
        response = requests.get(ROR_API_ENDPOINT + '?' + f'query="{nom_univ}"').json()
        if response["number_of_results"] > 1 :
            for n, x in enumerate(response["items"]):
                if 'education' in x["types"] :
                    datas = response["items"][n]
                    rors = datas["id"]
        elif response["number_of_results"] == 1 :
            datas = response["items"][0]
            rors = datas["id"]
        else:
             rors = "not found"
        dict_ror2[a] = rors
    except:
        print(nom_univ)

In [ ]:
dict_ror2
#len(df_ad2)

In [ ]:
dict_ror2
df_ad2["ror"] = df_ad2.address.map(dict_ror2.get)
df_ad2